export type FacilityType = 'hospital_publico' | 'cesfam' | 'clinica_privada';

export interface Facility {
  id: string;
  name: string;
  type: FacilityType;
  typeLabel: string;
  address: string;
  comuna: string;
  phone: string;
  latitude: number;
  longitude: number;
  hours: string;
  services: string[];
  description: string;
  urgencia: boolean;
  googleRating: number;
  googleReviews: number;
  attendanceRate: string;
}

export const facilityTypeConfig: Record<FacilityType, { label: string; color: string; lightColor: string; icon: string }> = {
  hospital_publico: {
    label: 'Hospital Público',
    color: '#DC2626',
    lightColor: '#FEE2E2',
    icon: 'local-hospital',
  },
  cesfam: {
    label: 'CESFAM',
    color: '#059669',
    lightColor: '#D1FAE5',
    icon: 'health-and-safety',
  },
  clinica_privada: {
    label: 'Clínica Privada',
    color: '#7C3AED',
    lightColor: '#EDE9FE',
    icon: 'medical-services',
  },
};

export const facilities: Facility[] = [
  // ═══════════════════════════════════════
  // HOSPITALES PÚBLICOS (15)
  // ═══════════════════════════════════════
  {
    id: 'hp-01',
    name: 'Hospital San José',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. San José 1196',
    comuna: 'Independencia',
    phone: '+56 2 2568 4000',
    latitude: -33.4195,
    longitude: -70.6518,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía General', 'Pediatría', 'Ginecología y Obstetricia', 'Traumatología', 'UCI', 'Imagenología'],
    description: 'Hospital público de alta complejidad perteneciente al Servicio de Salud Metropolitano Norte. Atiende a la población de las comunas del sector norte de Santiago.',
    urgencia: true,
    googleRating: 3.2,
    googleReviews: 4823,
    attendanceRate: '~1.200 pacientes/día',
  },
  {
    id: 'hp-02',
    name: 'Hospital San Juan de Dios',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Portales 3239',
    comuna: 'Santiago',
    phone: '+56 2 2574 8000',
    latitude: -33.4510,
    longitude: -70.6820,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Neurología', 'Cardiología', 'Nefrología', 'UCI', 'Neonatología'],
    description: 'Uno de los hospitales más antiguos de Chile, ubicado en el centro de Santiago. Ofrece atención de alta complejidad para el sector occidente de la capital.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 5102,
    attendanceRate: '~1.400 pacientes/día',
  },
  {
    id: 'hp-03',
    name: 'Hospital Clínico San Borja Arriarán',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Santa Rosa 1234',
    comuna: 'Santiago',
    phone: '+56 2 2574 0100',
    latitude: -33.4505,
    longitude: -70.6478,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Dermatología', 'Oftalmología', 'UCI'],
    description: 'Hospital de alta complejidad del Servicio de Salud Metropolitano Central, ubicado en el corazón de Santiago. Referente en diversas especialidades médicas.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 3956,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'hp-04',
    name: 'Hospital Barros Luco Trudeau',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. José Miguel Carrera 3204',
    comuna: 'San Miguel',
    phone: '+56 2 2394 8000',
    latitude: -33.4920,
    longitude: -70.6560,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Traumatología', 'Neurocirugía', 'Cardiología', 'UCI', 'Diálisis'],
    description: 'Hospital de referencia del sector sur de Santiago. Cuenta con un amplio servicio de urgencia y especialidades de alta complejidad.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 4210,
    attendanceRate: '~1.350 pacientes/día',
  },
  {
    id: 'hp-05',
    name: 'Hospital Dr. Sótero del Río',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Concha y Toro 3459',
    comuna: 'Puente Alto',
    phone: '+56 2 2576 2600',
    latitude: -33.5830,
    longitude: -70.5750,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Maternidad', 'Traumatología', 'UCI', 'Laboratorio'],
    description: 'Principal hospital público del sector suroriente de Santiago, atendiendo a las comunas de Puente Alto, La Pintana, San José de Maipo y Pirque.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 6230,
    attendanceRate: '~1.600 pacientes/día',
  },
  {
    id: 'hp-06',
    name: 'Hospital Padre Hurtado',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Esperanza 2150',
    comuna: 'San Ramón',
    phone: '+56 2 2576 7700',
    latitude: -33.5340,
    longitude: -70.6350,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Hospital de mediana complejidad que atiende a las comunas de San Ramón, La Granja y La Pintana. Inaugurado en 2001.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2870,
    attendanceRate: '~850 pacientes/día',
  },
  {
    id: 'hp-07',
    name: 'Hospital El Pino',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Santiago Bueras 1003',
    comuna: 'San Bernardo',
    phone: '+56 2 2488 6000',
    latitude: -33.5920,
    longitude: -70.7050,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Laboratorio'],
    description: 'Hospital de mediana complejidad ubicado en San Bernardo, atendiendo al sector sur-poniente del área metropolitana.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 3415,
    attendanceRate: '~900 pacientes/día',
  },
  {
    id: 'hp-08',
    name: 'Hospital Félix Bulnes Cerda',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Mapocho 7432',
    comuna: 'Cerro Navia',
    phone: '+56 2 2574 5600',
    latitude: -33.4240,
    longitude: -70.7310,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'UCI Neonatal'],
    description: 'Hospital público del sector norponiente de Santiago. Inaugurado en su nuevo edificio, cuenta con modernas instalaciones y tecnología de punta.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 2145,
    attendanceRate: '~950 pacientes/día',
  },
  {
    id: 'hp-09',
    name: 'Hospital de Niños Roberto del Río',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Profesor Zañartu 1085',
    comuna: 'Independencia',
    phone: '+56 2 2575 5400',
    latitude: -33.4170,
    longitude: -70.6540,
    hours: '24 horas',
    services: ['Urgencia Pediátrica', 'Pediatría', 'Cirugía Infantil', 'Neurología Infantil', 'Cardiología Infantil', 'UCI Pediátrica', 'Neonatología'],
    description: 'Principal hospital pediátrico del norte de Santiago. Centro de referencia nacional en especialidades infantiles de alta complejidad.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 3890,
    attendanceRate: '~800 pacientes/día',
  },
  {
    id: 'hp-10',
    name: 'Hospital Dr. Exequiel González Cortés',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Ramón Barros Luco 3301',
    comuna: 'San Miguel',
    phone: '+56 2 2576 4800',
    latitude: -33.4970,
    longitude: -70.6590,
    hours: '24 horas',
    services: ['Urgencia Pediátrica', 'Pediatría', 'Cirugía Infantil', 'Traumatología Infantil', 'UCI Pediátrica', 'Odontología Infantil'],
    description: 'Hospital pediátrico de referencia del sector sur de Santiago, especializado en la atención integral de niños y adolescentes.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 2760,
    attendanceRate: '~700 pacientes/día',
  },
  {
    id: 'hp-11',
    name: 'Hospital Clínico Universidad de Chile',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Santos Dumont 999',
    comuna: 'Independencia',
    phone: '+56 2 2978 8000',
    latitude: -33.4155,
    longitude: -70.6490,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Oncología', 'Cardiología', 'Neurología', 'Trasplantes', 'UCI'],
    description: 'Hospital universitario de alta complejidad, referente nacional en docencia médica, investigación clínica y trasplantes de órganos.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 5840,
    attendanceRate: '~1.300 pacientes/día',
  },
  {
    id: 'hp-12',
    name: 'Hospital del Salvador',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Salvador 364',
    comuna: 'Providencia',
    phone: '+56 2 2575 4000',
    latitude: -33.4385,
    longitude: -70.6270,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Reumatología', 'Oftalmología', 'Dermatología', 'Geriatría', 'UCI'],
    description: 'Hospital público de alta complejidad perteneciente al Servicio de Salud Metropolitano Oriente, referente en reumatología y oftalmología.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 4120,
    attendanceRate: '~1.050 pacientes/día',
  },
  {
    id: 'hp-13',
    name: 'Hospital San Borja Arriarán - Complejo Asistencial',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Natalio Cox 44',
    comuna: 'Santiago',
    phone: '+56 2 2574 0200',
    latitude: -33.4470,
    longitude: -70.6530,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Traumatología', 'Cirugía Plástica', 'Quemados', 'UCI', 'Rehabilitación'],
    description: 'Centro asistencial especializado del Servicio de Salud Metropolitano Central, destacado por su unidad de grandes quemados.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 2310,
    attendanceRate: '~750 pacientes/día',
  },
  {
    id: 'hp-14',
    name: 'Hospital de La Florida',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Froilán Roa 6542',
    comuna: 'La Florida',
    phone: '+56 2 2576 9000',
    latitude: -33.5200,
    longitude: -70.5980,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'UCI', 'Imagenología'],
    description: 'Hospital público de alta complejidad inaugurado en 2014, equipado con tecnología moderna para atender a la comuna más poblada de Santiago.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 3650,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'hp-15',
    name: 'Hospital de Maipú',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Camino a Rinconada 1201',
    comuna: 'Maipú',
    phone: '+56 2 2576 5000',
    latitude: -33.5100,
    longitude: -70.7570,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Neonatología', 'UCI'],
    description: 'Hospital moderno de alta complejidad inaugurado en 2018 para atender a las comunas de Maipú y Cerrillos del sector poniente de Santiago.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2980,
    attendanceRate: '~1.000 pacientes/día',
  },

  // ═══════════════════════════════════════
  // CLÍNICAS PRIVADAS (15)
  // ═══════════════════════════════════════
  {
    id: 'cp-01',
    name: 'Clínica Alemana',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Vitacura 5951',
    comuna: 'Vitacura',
    phone: '+56 2 2210 1111',
    latitude: -33.3970,
    longitude: -70.5910,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Neurología', 'Imagenología', 'Laboratorio', 'UCI'],
    description: 'Una de las clínicas más prestigiosas de Chile y Sudamérica, reconocida por su excelencia médica, tecnología de vanguardia e investigación clínica.',
    urgencia: true,
    googleRating: 4.3,
    googleReviews: 12540,
    attendanceRate: '~2.500 pacientes/día',
  },
  {
    id: 'cp-02',
    name: 'Clínica Las Condes',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Lo Fontecilla 441',
    comuna: 'Las Condes',
    phone: '+56 2 2210 4000',
    latitude: -33.4080,
    longitude: -70.5700,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía Robótica', 'Cardiología', 'Oncología', 'Neurocirugía', 'Traumatología', 'Centro de Trasplantes'],
    description: 'Clínica de alta complejidad ubicada en Las Condes, reconocida internacionalmente por su programa de trasplantes y cirugía robótica.',
    urgencia: true,
    googleRating: 4.2,
    googleReviews: 10870,
    attendanceRate: '~2.200 pacientes/día',
  },
  {
    id: 'cp-03',
    name: 'Clínica Santa María',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Santa María 0500',
    comuna: 'Providencia',
    phone: '+56 2 2913 0000',
    latitude: -33.4220,
    longitude: -70.6180,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Maternidad', 'Pediatría', 'Cardiología', 'Traumatología', 'Imagenología'],
    description: 'Clínica de larga trayectoria en Providencia, reconocida por su servicio de maternidad y atención integral de la familia.',
    urgencia: true,
    googleRating: 4.0,
    googleReviews: 8940,
    attendanceRate: '~1.800 pacientes/día',
  },
  {
    id: 'cp-04',
    name: 'Clínica Dávila',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Recoleta 464',
    comuna: 'Recoleta',
    phone: '+56 2 2730 8000',
    latitude: -33.4290,
    longitude: -70.6420,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Neurología', 'UCI', 'Diálisis'],
    description: 'Centro de salud integral ubicado en Recoleta, con amplia cobertura de especialidades y atención a pacientes Fonasa e Isapre.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 7620,
    attendanceRate: '~1.900 pacientes/día',
  },
  {
    id: 'cp-05',
    name: 'Clínica Indisa',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Santa María 1810',
    comuna: 'Providencia',
    phone: '+56 2 2362 5555',
    latitude: -33.4250,
    longitude: -70.6120,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Ginecología', 'Traumatología', 'Dermatología', 'Oftalmología'],
    description: 'Clínica ubicada en Providencia con más de 40 años de experiencia, ofreciendo atención médica integral y cercana.',
    urgencia: true,
    googleRating: 3.9,
    googleReviews: 5430,
    attendanceRate: '~1.200 pacientes/día',
  },
  {
    id: 'cp-06',
    name: 'Clínica Universidad de los Andes',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Plaza 2501',
    comuna: 'Las Condes',
    phone: '+56 2 2618 3000',
    latitude: -33.3850,
    longitude: -70.5490,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Cardiología', 'Imagenología', 'Laboratorio'],
    description: 'Clínica universitaria con enfoque académico y asistencial, combinando docencia, investigación y atención médica de excelencia.',
    urgencia: true,
    googleRating: 4.1,
    googleReviews: 4560,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'cp-07',
    name: 'Clínica Bicentenario',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Américo Vespucio Sur 501',
    comuna: 'La Florida',
    phone: '+56 2 2366 2100',
    latitude: -33.5180,
    longitude: -70.5920,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Maternidad', 'Pediatría', 'Traumatología', 'Imagenología'],
    description: 'Clínica moderna ubicada en La Florida, ofreciendo atención de calidad al sector suroriente de Santiago con convenios Fonasa.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 3890,
    attendanceRate: '~1.050 pacientes/día',
  },
  {
    id: 'cp-08',
    name: 'Clínica Vespucio',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Américo Vespucio 1100',
    comuna: 'La Florida',
    phone: '+56 2 2485 7000',
    latitude: -33.5260,
    longitude: -70.5870,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Ginecología', 'Traumatología', 'Otorrinolaringología', 'Laboratorio'],
    description: 'Clínica integral en La Florida que destaca por su cercanía con la comunidad y atención expedita en urgencias.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 2940,
    attendanceRate: '~900 pacientes/día',
  },
  {
    id: 'cp-09',
    name: 'Clínica RedSalud Santiago',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Apoquindo 3990',
    comuna: 'Las Condes',
    phone: '+56 2 2822 0600',
    latitude: -33.4120,
    longitude: -70.5810,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía Ambulatoria', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Parte de la red RedSalud, ofrece atención accesible con múltiples especialidades y convenios con Fonasa e Isapres.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2380,
    attendanceRate: '~750 pacientes/día',
  },
  {
    id: 'cp-10',
    name: 'Clínica MEDS',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Isabel La Católica 3740',
    comuna: 'Las Condes',
    phone: '+56 2 2916 3000',
    latitude: -33.3980,
    longitude: -70.5580,
    hours: 'Lunes a Sábado 8:00 - 20:00',
    services: ['Traumatología Deportiva', 'Kinesiología', 'Cirugía Ortopédica', 'Medicina Deportiva', 'Imagenología', 'Rehabilitación'],
    description: 'Clínica especializada en medicina deportiva y traumatología, referente en Chile para deportistas profesionales y amateurs.',
    urgencia: false,
    googleRating: 4.4,
    googleReviews: 6120,
    attendanceRate: '~600 pacientes/día',
  },
  {
    id: 'cp-11',
    name: 'Clínica Tabancura',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Tabancura 1185',
    comuna: 'Vitacura',
    phone: '+56 2 2210 7000',
    latitude: -33.3930,
    longitude: -70.5770,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Maternidad', 'Pediatría', 'Ginecología', 'Traumatología'],
    description: 'Clínica del grupo Red de Salud UC CHRISTUS ubicada en Vitacura, con especial énfasis en maternidad y atención pediátrica.',
    urgencia: true,
    googleRating: 4.0,
    googleReviews: 3210,
    attendanceRate: '~800 pacientes/día',
  },
  {
    id: 'cp-12',
    name: 'Clínica RedSalud Providencia',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Salvador 130',
    comuna: 'Providencia',
    phone: '+56 2 2592 5000',
    latitude: -33.4370,
    longitude: -70.6240,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía Ambulatoria', 'Ginecología', 'Dermatología', 'Oftalmología', 'Laboratorio'],
    description: 'Centro de salud de la red RedSalud con atención integral y ubicación estratégica en el corazón de Providencia.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 2670,
    attendanceRate: '~680 pacientes/día',
  },
  {
    id: 'cp-13',
    name: 'Clínica Dávila Vespucio',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Vicuña Mackenna 6570',
    comuna: 'La Florida',
    phone: '+56 2 2730 9000',
    latitude: -33.5140,
    longitude: -70.5990,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'UCI', 'Imagenología'],
    description: 'Extensión de Clínica Dávila en el sector suroriente de Santiago, con moderna infraestructura y convenios Fonasa.',
    urgencia: true,
    googleRating: 3.9,
    googleReviews: 4180,
    attendanceRate: '~1.150 pacientes/día',
  },
  {
    id: 'cp-14',
    name: 'Clínica UC CHRISTUS',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Lira 40',
    comuna: 'Santiago',
    phone: '+56 2 2354 3000',
    latitude: -33.4440,
    longitude: -70.6430,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Neurocirugía', 'Trasplantes', 'UCI'],
    description: 'Centro médico académico de la Pontificia Universidad Católica, reconocido como uno de los mejores centros de salud de América Latina.',
    urgencia: true,
    googleRating: 4.5,
    googleReviews: 9870,
    attendanceRate: '~2.000 pacientes/día',
  },
  {
    id: 'cp-15',
    name: 'Clínica Bupa Santiago',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Manuel Montt 115',
    comuna: 'Providencia',
    phone: '+56 2 2366 7000',
    latitude: -33.4310,
    longitude: -70.6200,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Cardiología', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Parte de la red internacional Bupa, esta clínica en Providencia ofrece estándares de salud globales con enfoque en prevención.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 3450,
    attendanceRate: '~950 pacientes/día',
  },

  // ═══════════════════════════════════════
  // CESFAM (15)
  // ═══════════════════════════════════════
  {
    id: 'ces-01',
    name: 'CESFAM Nº1 Ramón Corbalán Melgarejo',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Portugal 205',
    comuna: 'Santiago',
    phone: '+56 2 2639 4920',
    latitude: -33.4480,
    longitude: -70.6380,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Programa de Vacunación', 'Control de Embarazo'],
    description: 'Centro de salud familiar ubicado en Santiago Centro, ofrece atención primaria integral para toda la familia con enfoque preventivo.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 1240,
    attendanceRate: '~350 pacientes/día',
  },
  {
    id: 'ces-02',
    name: 'CESFAM Cristo Vive',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Recoleta 3601',
    comuna: 'Recoleta',
    phone: '+56 2 2621 7880',
    latitude: -33.4100,
    longitude: -70.6420,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Medicina Complementaria', 'Salud Mental', 'Kinesiología'],
    description: 'Centro de salud con enfoque intercultural en Recoleta, reconocido por integrar medicina complementaria y atención a población migrante.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 890,
    attendanceRate: '~320 pacientes/día',
  },
  {
    id: 'ces-03',
    name: 'CESFAM Lo Barnechea',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Lo Barnechea 1101',
    comuna: 'Lo Barnechea',
    phone: '+56 2 2216 8700',
    latitude: -33.3550,
    longitude: -70.5200,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Programa del Adulto Mayor', 'Vacunación', 'Control de Niño Sano'],
    description: 'Centro de salud familiar que atiende a la comunidad de Lo Barnechea con programas de salud preventiva y promocional.',
    urgencia: false,
    googleRating: 3.6,
    googleReviews: 640,
    attendanceRate: '~280 pacientes/día',
  },
  {
    id: 'ces-04',
    name: 'CESFAM Padre Gerardo Whelan',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. José Joaquín Pérez 8630',
    comuna: 'Cerro Navia',
    phone: '+56 2 2640 1250',
    latitude: -33.4260,
    longitude: -70.7380,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Kinesiología', 'Nutrición'],
    description: 'CESFAM comunitario en Cerro Navia con fuerte enfoque en salud familiar y programas de participación comunitaria.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 710,
    attendanceRate: '~400 pacientes/día',
  },
  {
    id: 'ces-05',
    name: 'CESFAM San Alberto Hurtado',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Concha y Toro 1820',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 6300',
    latitude: -33.5700,
    longitude: -70.5850,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Programa Cardiovascular', 'Vacunación', 'Salud Mental'],
    description: 'Centro de salud familiar en Puente Alto que brinda atención primaria a una de las comunas más pobladas de Santiago.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 980,
    attendanceRate: '~450 pacientes/día',
  },
  {
    id: 'ces-06',
    name: 'CESFAM Carol Urzúa Ibáñez',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Lo Ovalle 01650',
    comuna: 'Pedro Aguirre Cerda',
    phone: '+56 2 2556 2100',
    latitude: -33.4830,
    longitude: -70.6640,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Kinesiología', 'Programa de Lactancia', 'Nutrición'],
    description: 'Centro de salud familiar en Pedro Aguirre Cerda, orientado a la atención integral con especial énfasis en salud materno-infantil.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 560,
    attendanceRate: '~310 pacientes/día',
  },
  {
    id: 'ces-07',
    name: 'CESFAM Lo Hermida',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Grecia 8777',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 5500',
    latitude: -33.4780,
    longitude: -70.5530,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Terapia Ocupacional', 'Podología'],
    description: 'Centro de salud comunitario en Peñalolén con larga trayectoria de servicio a la comunidad de Lo Hermida.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 830,
    attendanceRate: '~370 pacientes/día',
  },
  {
    id: 'ces-08',
    name: 'CESFAM Juan Antonio Ríos',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. El Guanaco 1331',
    comuna: 'Independencia',
    phone: '+56 2 2737 3200',
    latitude: -33.4080,
    longitude: -70.6600,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Programa del Adulto Mayor', 'Control Prenatal', 'Vacunación'],
    description: 'CESFAM en la comuna de Independencia que atiende a la población del sector norte con programas preventivos y de control.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 620,
    attendanceRate: '~340 pacientes/día',
  },
  {
    id: 'ces-09',
    name: 'CESFAM Bellavista de La Florida',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Bellavista 3450',
    comuna: 'La Florida',
    phone: '+56 2 2281 1900',
    latitude: -33.5250,
    longitude: -70.5930,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Nutrición', 'Programa Cardiovascular'],
    description: 'Centro de salud en La Florida con fuerte presencia comunitaria y programas de promoción de estilos de vida saludable.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 740,
    attendanceRate: '~380 pacientes/día',
  },
  {
    id: 'ces-10',
    name: 'CESFAM El Roble',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Santa Rosa 12850',
    comuna: 'La Pintana',
    phone: '+56 2 2542 7800',
    latitude: -33.5600,
    longitude: -70.6340,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Kinesiología', 'Vacunación', 'Salud Mental'],
    description: 'CESFAM de La Pintana enfocado en la atención primaria integral con programas de salud comunitaria y participación ciudadana.',
    urgencia: false,
    googleRating: 2.7,
    googleReviews: 510,
    attendanceRate: '~420 pacientes/día',
  },
  {
    id: 'ces-11',
    name: 'CESFAM Ñuñoa',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Irarrázaval 4054',
    comuna: 'Ñuñoa',
    phone: '+56 2 2239 4500',
    latitude: -33.4540,
    longitude: -70.6010,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Kinesiología', 'Control de Niño Sano'],
    description: 'Centro de salud familiar de la comuna de Ñuñoa con enfoque preventivo y de promoción de la salud para toda la comunidad.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 920,
    attendanceRate: '~330 pacientes/día',
  },
  {
    id: 'ces-12',
    name: 'CESFAM Maipú',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Los Pajaritos 3391',
    comuna: 'Maipú',
    phone: '+56 2 2531 8200',
    latitude: -33.5090,
    longitude: -70.7640,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Nutrición', 'Programa Cardiovascular', 'Vacunación'],
    description: 'CESFAM de la comuna de Maipú que atiende a una gran cantidad de población del sector poniente con programas de salud familiar.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 1120,
    attendanceRate: '~480 pacientes/día',
  },
  {
    id: 'ces-13',
    name: 'CESFAM Quilicura',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. San Martín 540',
    comuna: 'Quilicura',
    phone: '+56 2 2948 3600',
    latitude: -33.3630,
    longitude: -70.7340,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Programa del Adulto Mayor', 'Vacunación'],
    description: 'Centro de salud familiar de Quilicura con atención intercultural para la diversa población de la comuna norponiente de Santiago.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 680,
    attendanceRate: '~410 pacientes/día',
  },
  {
    id: 'ces-14',
    name: 'CESFAM La Reina',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Príncipe de Gales 6832',
    comuna: 'La Reina',
    phone: '+56 2 2273 6100',
    latitude: -33.4490,
    longitude: -70.5450,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Nutrición', 'Kinesiología', 'Programa de Vacunación'],
    description: 'Centro de salud familiar de La Reina con enfoque en atención primaria de calidad y programas de salud preventiva.',
    urgencia: false,
    googleRating: 3.6,
    googleReviews: 530,
    attendanceRate: '~260 pacientes/día',
  },
  {
    id: 'ces-15',
    name: 'CESFAM Macul',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Macul 3450',
    comuna: 'Macul',
    phone: '+56 2 2238 9200',
    latitude: -33.4740,
    longitude: -70.5940,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Terapia Ocupacional', 'Control Prenatal'],
    description: 'CESFAM de la comuna de Macul con fuerte vínculo comunitario y programas orientados a la salud familiar integral.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 470,
    attendanceRate: '~290 pacientes/día',
  },
];
