export type FacilityType =
  | 'hospital_publico'
  | 'hospital_universitario'
  | 'cesfam'
  | 'clinica_privada'
  | 'sapu'
  | 'sar'
  | 'cosam'
  | 'cecof'
  | 'aseguradora'
  | 'mutual';

export interface Facility {
  id: string;
  name: string;
  type: FacilityType;
  typeLabel: string;
  address: string;
  comuna: string;
  phone: string;
  latitude: number;
  longitude: number;
  hours: string;
  services: string[];
  description: string;
  urgencia: boolean;
  googleRating: number;
  googleReviews: number;
  attendanceRate: string;
}

export const facilityTypeConfig: Record<
  FacilityType,
  { label: string; color: string; lightColor: string; icon: string }
> = {
  hospital_publico: {
    label: 'Hospital Público',
    color: '#DC2626',
    lightColor: '#FEE2E2',
    icon: 'local-hospital',
  },
  hospital_universitario: {
    label: 'Hospital Universitario',
    color: '#0369A1',
    lightColor: '#E0F2FE',
    icon: 'school',
  },
  cesfam: {
    label: 'CESFAM',
    color: '#059669',
    lightColor: '#D1FAE5',
    icon: 'health-and-safety',
  },
  clinica_privada: {
    label: 'Clínica Privada',
    color: '#7C3AED',
    lightColor: '#EDE9FE',
    icon: 'medical-services',
  },
  sapu: {
    label: 'SAPU',
    color: '#EA580C',
    lightColor: '#FFEDD5',
    icon: 'emergency',
  },
  sar: {
    label: 'SAR',
    color: '#D97706',
    lightColor: '#FEF3C7',
    icon: 'bolt',
  },
  cosam: {
    label: 'COSAM',
    color: '#4F46E5',
    lightColor: '#E0E7FF',
    icon: 'psychology',
  },
  cecof: {
    label: 'CECOF',
    color: '#0891B2',
    lightColor: '#CFFAFE',
    icon: 'groups',
  },
  aseguradora: {
    label: 'Aseguradora',
    color: '#2563EB',
    lightColor: '#DBEAFE',
    icon: 'verified-user',
  },
  mutual: {
    label: 'Mutual',
    color: '#9333EA',
    lightColor: '#F3E8FF',
    icon: 'shield',
  },
};

export const facilities: Facility[] = [
  // ═══════════════════════════════════════
  // HOSPITALES PÚBLICOS (18)
  // ═══════════════════════════════════════
  {
    id: 'hp-01',
    name: 'Hospital San José',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'San José 1196, Independencia',
    comuna: 'Independencia',
    phone: '+56 2 2568 4000',
    latitude: -33.4195,
    longitude: -70.6518,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía General', 'Pediatría', 'Ginecología y Obstetricia', 'Traumatología', 'UCI', 'Imagenología'],
    description: 'Hospital público de alta complejidad del Servicio de Salud Metropolitano Norte.',
    urgencia: true,
    googleRating: 3.2,
    googleReviews: 4823,
    attendanceRate: '~1.200 pacientes/día',
  },
  {
    id: 'hp-02',
    name: 'Hospital San Juan de Dios',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Huérfanos 3255, Santiago',
    comuna: 'Santiago',
    phone: '+56 2 2574 8000',
    latitude: -33.4488,
    longitude: -70.6784,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Neurología', 'Cardiología', 'Nefrología', 'UCI', 'Neonatología'],
    description: 'Uno de los hospitales más antiguos de Chile, ubicado en el centro de Santiago.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 5102,
    attendanceRate: '~1.400 pacientes/día',
  },
  {
    id: 'hp-03',
    name: 'Hospital Clínico San Borja Arriarán',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Santa Rosa 1234, Santiago',
    comuna: 'Santiago',
    phone: '+56 2 2574 0100',
    latitude: -33.4530,
    longitude: -70.6440,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Dermatología', 'Oftalmología', 'UCI'],
    description: 'Hospital de alta complejidad del Servicio de Salud Metropolitano Central.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 3956,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'hp-04',
    name: 'Hospital Barros Luco Trudeau',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'José Miguel Carrera 3204, San Miguel',
    comuna: 'San Miguel',
    phone: '+56 2 2394 8000',
    latitude: -33.4921,
    longitude: -70.6558,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Traumatología', 'Neurocirugía', 'Cardiología', 'UCI', 'Diálisis'],
    description: 'Hospital de referencia del sector sur de Santiago con amplio servicio de urgencia.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 4210,
    attendanceRate: '~1.350 pacientes/día',
  },
  {
    id: 'hp-05',
    name: 'Hospital Dr. Sótero del Río',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Concha y Toro 3459, Puente Alto',
    comuna: 'Puente Alto',
    phone: '+56 2 2576 2600',
    latitude: -33.5829,
    longitude: -70.5752,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Maternidad', 'Traumatología', 'UCI', 'Laboratorio'],
    description: 'Principal hospital público del sector suroriente de Santiago.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 6230,
    attendanceRate: '~1.600 pacientes/día',
  },
  {
    id: 'hp-06',
    name: 'Hospital Padre Hurtado',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Esperanza 2150, San Ramón',
    comuna: 'San Ramón',
    phone: '+56 2 2576 7700',
    latitude: -33.5340,
    longitude: -70.6350,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Hospital de mediana complejidad que atiende a San Ramón, La Granja y La Pintana.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2870,
    attendanceRate: '~850 pacientes/día',
  },
  {
    id: 'hp-07',
    name: 'Hospital El Pino',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Santiago Bueras 1003, San Bernardo',
    comuna: 'San Bernardo',
    phone: '+56 2 2488 6000',
    latitude: -33.5920,
    longitude: -70.7050,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Laboratorio'],
    description: 'Hospital de mediana complejidad ubicado en San Bernardo.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 3415,
    attendanceRate: '~900 pacientes/día',
  },
  {
    id: 'hp-08',
    name: 'Hospital Félix Bulnes Cerda',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Leoncio Fernández 2655, Quinta Normal',
    comuna: 'Quinta Normal',
    phone: '+56 2 2574 5600',
    latitude: -33.4270,
    longitude: -70.7120,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'UCI Neonatal'],
    description: 'Hospital público del sector norponiente de Santiago con modernas instalaciones.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 2145,
    attendanceRate: '~950 pacientes/día',
  },
  {
    id: 'hp-09',
    name: 'Hospital de Niños Roberto del Río',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Profesor Zañartu 1085, Independencia',
    comuna: 'Independencia',
    phone: '+56 2 2575 5400',
    latitude: -33.4170,
    longitude: -70.6540,
    hours: '24 horas',
    services: ['Urgencia Pediátrica', 'Pediatría', 'Cirugía Infantil', 'Neurología Infantil', 'Cardiología Infantil', 'UCI Pediátrica'],
    description: 'Principal hospital pediátrico del norte de Santiago.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 3890,
    attendanceRate: '~800 pacientes/día',
  },
  {
    id: 'hp-10',
    name: 'Hospital Dr. Exequiel González Cortés',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Ramón Barros Luco 3301, San Miguel',
    comuna: 'San Miguel',
    phone: '+56 2 2576 4800',
    latitude: -33.4970,
    longitude: -70.6590,
    hours: '24 horas',
    services: ['Urgencia Pediátrica', 'Pediatría', 'Cirugía Infantil', 'Traumatología Infantil', 'UCI Pediátrica'],
    description: 'Hospital pediátrico de referencia del sector sur de Santiago.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 2760,
    attendanceRate: '~700 pacientes/día',
  },
  {
    id: 'hp-11',
    name: 'Hospital del Salvador',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Salvador 364, Providencia',
    comuna: 'Providencia',
    phone: '+56 2 2575 4000',
    latitude: -33.4385,
    longitude: -70.6270,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Reumatología', 'Oftalmología', 'Dermatología', 'Geriatría', 'UCI'],
    description: 'Hospital público de alta complejidad del SSMSO, referente en reumatología.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 4120,
    attendanceRate: '~1.050 pacientes/día',
  },
  {
    id: 'hp-12',
    name: 'Hospital de La Florida Dra. Eloísa Díaz',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Froilán Roa 6542, La Florida',
    comuna: 'La Florida',
    phone: '+56 2 2576 9000',
    latitude: -33.5200,
    longitude: -70.5980,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'UCI', 'Imagenología'],
    description: 'Hospital público de alta complejidad inaugurado en 2014.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 3650,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'hp-13',
    name: 'Hospital de Maipú',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Camino a Rinconada 1201, Maipú',
    comuna: 'Maipú',
    phone: '+56 2 2576 5000',
    latitude: -33.5100,
    longitude: -70.7570,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Neonatología', 'UCI'],
    description: 'Hospital moderno de alta complejidad inaugurado en 2018.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2980,
    attendanceRate: '~1.000 pacientes/día',
  },
  {
    id: 'hp-14',
    name: 'Hospital San Luis de Buin',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Maipú 1001, Buin',
    comuna: 'Buin',
    phone: '+56 2 2821 3000',
    latitude: -33.7310,
    longitude: -70.7420,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía Menor', 'Pediatría', 'Ginecología', 'Laboratorio'],
    description: 'Hospital comunitario de Buin para atención primaria y de mediana complejidad.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 1240,
    attendanceRate: '~450 pacientes/día',
  },
  {
    id: 'hp-15',
    name: 'Hospital de Melipilla',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Ortúzar 201, Melipilla',
    comuna: 'Melipilla',
    phone: '+56 2 2832 1000',
    latitude: -33.6860,
    longitude: -71.2140,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Laboratorio', 'Imagenología'],
    description: 'Hospital público de mediana complejidad para la provincia de Melipilla.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 2180,
    attendanceRate: '~700 pacientes/día',
  },
  {
    id: 'hp-16',
    name: 'Hospital de Talagante',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Balmaceda 1458, Talagante',
    comuna: 'Talagante',
    phone: '+56 2 2815 7000',
    latitude: -33.6640,
    longitude: -70.9260,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía Menor', 'Pediatría', 'Ginecología', 'Laboratorio'],
    description: 'Hospital comunitario de la provincia de Talagante.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 1450,
    attendanceRate: '~500 pacientes/día',
  },
  {
    id: 'hp-17',
    name: 'Hospital de Peñaflor',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Vicuña Mackenna 100, Peñaflor',
    comuna: 'Peñaflor',
    phone: '+56 2 2812 5000',
    latitude: -33.6100,
    longitude: -70.8770,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Pediatría', 'Ginecología', 'Laboratorio'],
    description: 'Hospital de baja complejidad de la comuna de Peñaflor.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 890,
    attendanceRate: '~350 pacientes/día',
  },
  {
    id: 'hp-18',
    name: 'Hospital de Colina',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Cristóbal Colón 101, Colina',
    comuna: 'Colina',
    phone: '+56 2 2844 7000',
    latitude: -33.2020,
    longitude: -70.6720,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía Menor', 'Pediatría', 'Ginecología', 'Laboratorio'],
    description: 'Hospital de la provincia de Chacabuco para la creciente población de Colina.',
    urgencia: true,
    googleRating: 3.2,
    googleReviews: 1560,
    attendanceRate: '~500 pacientes/día',
  },

  // ═══════════════════════════════════════
  // HOSPITALES UNIVERSITARIOS (6)
  // ═══════════════════════════════════════
  {
    id: 'hu-01',
    name: 'Hospital Clínico Universidad de Chile',
    type: 'hospital_universitario',
    typeLabel: 'Hospital Universitario',
    address: 'Santos Dumont 999, Independencia',
    comuna: 'Independencia',
    phone: '+56 2 2978 8000',
    latitude: -33.4155,
    longitude: -70.6490,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Oncología', 'Cardiología', 'Neurología', 'Trasplantes', 'UCI'],
    description: 'Hospital universitario de alta complejidad, referente nacional en docencia médica e investigación clínica.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 5840,
    attendanceRate: '~1.300 pacientes/día',
  },
  {
    id: 'hu-02',
    name: 'Hospital Clínico UC CHRISTUS',
    type: 'hospital_universitario',
    typeLabel: 'Hospital Universitario',
    address: 'Lira 40, Santiago',
    comuna: 'Santiago',
    phone: '+56 2 2354 3000',
    latitude: -33.4440,
    longitude: -70.6430,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Neurocirugía', 'Trasplantes', 'UCI'],
    description: 'Centro médico académico de la Pontificia Universidad Católica de Chile, uno de los mejores de América Latina.',
    urgencia: true,
    googleRating: 4.5,
    googleReviews: 9870,
    attendanceRate: '~2.000 pacientes/día',
  },
  {
    id: 'hu-03',
    name: 'Clínica Universidad de los Andes',
    type: 'hospital_universitario',
    typeLabel: 'Hospital Universitario',
    address: 'Plaza 2501, Las Condes',
    comuna: 'Las Condes',
    phone: '+56 2 2618 3000',
    latitude: -33.3850,
    longitude: -70.5490,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Cardiología', 'Imagenología'],
    description: 'Clínica universitaria con enfoque académico, docencia e investigación.',
    urgencia: true,
    googleRating: 4.1,
    googleReviews: 4560,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'hu-04',
    name: 'Hospital DIPRECA',
    type: 'hospital_universitario',
    typeLabel: 'Hospital Universitario',
    address: 'Vital Apoquindo 1200, Las Condes',
    comuna: 'Las Condes',
    phone: '+56 2 2464 8000',
    latitude: -33.4090,
    longitude: -70.5640,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Traumatología', 'UCI'],
    description: 'Hospital de la Dirección de Previsión de Carabineros, con campo clínico universitario.',
    urgencia: true,
    googleRating: 3.9,
    googleReviews: 2340,
    attendanceRate: '~800 pacientes/día',
  },
  {
    id: 'hu-05',
    name: 'Hospital Militar de Santiago',
    type: 'hospital_universitario',
    typeLabel: 'Hospital Universitario',
    address: 'Holanda 0177, Providencia',
    comuna: 'Providencia',
    phone: '+56 2 2365 8000',
    latitude: -33.4340,
    longitude: -70.6160,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Traumatología', 'Cardiología', 'Oncología', 'UCI'],
    description: 'Hospital institucional con campo clínico universitario de varias universidades.',
    urgencia: true,
    googleRating: 4.0,
    googleReviews: 3210,
    attendanceRate: '~900 pacientes/día',
  },
  {
    id: 'hu-06',
    name: 'Hospital FACH',
    type: 'hospital_universitario',
    typeLabel: 'Hospital Universitario',
    address: 'Las Condes 8631, Las Condes',
    comuna: 'Las Condes',
    phone: '+56 2 2782 6000',
    latitude: -33.3960,
    longitude: -70.5430,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Traumatología', 'Cardiología', 'Imagenología', 'UCI'],
    description: 'Hospital de la Fuerza Aérea de Chile con docencia universitaria.',
    urgencia: true,
    googleRating: 4.1,
    googleReviews: 1890,
    attendanceRate: '~600 pacientes/día',
  },

  // ═══════════════════════════════════════
  // CLÍNICAS PRIVADAS (16)
  // ═══════════════════════════════════════
  {
    id: 'cp-01',
    name: 'Clínica Alemana',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Vitacura 5951, Vitacura',
    comuna: 'Vitacura',
    phone: '+56 2 2210 1111',
    latitude: -33.3970,
    longitude: -70.5910,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Neurología', 'Imagenología', 'UCI'],
    description: 'Una de las clínicas más prestigiosas de Chile y Sudamérica.',
    urgencia: true,
    googleRating: 4.3,
    googleReviews: 12540,
    attendanceRate: '~2.500 pacientes/día',
  },
  {
    id: 'cp-02',
    name: 'Clínica Las Condes',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Lo Fontecilla 441, Las Condes',
    comuna: 'Las Condes',
    phone: '+56 2 2210 4000',
    latitude: -33.4080,
    longitude: -70.5700,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía Robótica', 'Cardiología', 'Oncología', 'Neurocirugía', 'Trasplantes'],
    description: 'Clínica de alta complejidad reconocida por su programa de trasplantes y cirugía robótica.',
    urgencia: true,
    googleRating: 4.2,
    googleReviews: 10870,
    attendanceRate: '~2.200 pacientes/día',
  },
  {
    id: 'cp-03',
    name: 'Clínica Santa María',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Santa María 0500, Providencia',
    comuna: 'Providencia',
    phone: '+56 2 2913 0000',
    latitude: -33.4220,
    longitude: -70.6180,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía', 'Maternidad', 'Pediatría', 'Cardiología', 'Traumatología'],
    description: 'Clínica de larga trayectoria reconocida por su servicio de maternidad.',
    urgencia: true,
    googleRating: 4.0,
    googleReviews: 8940,
    attendanceRate: '~1.800 pacientes/día',
  },
  {
    id: 'cp-04',
    name: 'Clínica Dávila',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Recoleta 464, Recoleta',
    comuna: 'Recoleta',
    phone: '+56 2 2730 8000',
    latitude: -33.4290,
    longitude: -70.6420,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'UCI', 'Diálisis'],
    description: 'Centro de salud integral con amplia cobertura de especialidades y convenios.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 7620,
    attendanceRate: '~1.900 pacientes/día',
  },
  {
    id: 'cp-05',
    name: 'Clínica Indisa',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Santa María 1810, Providencia',
    comuna: 'Providencia',
    phone: '+56 2 2362 5555',
    latitude: -33.4250,
    longitude: -70.6120,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía', 'Ginecología', 'Traumatología', 'Dermatología', 'Oftalmología'],
    description: 'Clínica con más de 40 años de experiencia en atención médica integral.',
    urgencia: true,
    googleRating: 3.9,
    googleReviews: 5430,
    attendanceRate: '~1.200 pacientes/día',
  },
  {
    id: 'cp-06',
    name: 'Clínica Bicentenario',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Américo Vespucio Sur 501, La Florida',
    comuna: 'La Florida',
    phone: '+56 2 2366 2100',
    latitude: -33.5180,
    longitude: -70.5920,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía', 'Maternidad', 'Pediatría', 'Traumatología'],
    description: 'Clínica moderna en La Florida con convenios Fonasa.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 3890,
    attendanceRate: '~1.050 pacientes/día',
  },
  {
    id: 'cp-07',
    name: 'Clínica Vespucio',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Américo Vespucio 1100, La Florida',
    comuna: 'La Florida',
    phone: '+56 2 2485 7000',
    latitude: -33.5260,
    longitude: -70.5870,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía', 'Ginecología', 'Traumatología', 'Laboratorio'],
    description: 'Clínica integral en La Florida con atención expedita en urgencias.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 2940,
    attendanceRate: '~900 pacientes/día',
  },
  {
    id: 'cp-08',
    name: 'Clínica RedSalud Santiago',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Apoquindo 3990, Las Condes',
    comuna: 'Las Condes',
    phone: '+56 2 2822 0600',
    latitude: -33.4120,
    longitude: -70.5810,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía Ambulatoria', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Parte de la red RedSalud con múltiples especialidades y convenios.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2380,
    attendanceRate: '~750 pacientes/día',
  },
  {
    id: 'cp-09',
    name: 'Clínica MEDS',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Isabel La Católica 3740, Las Condes',
    comuna: 'Las Condes',
    phone: '+56 2 2916 3000',
    latitude: -33.3980,
    longitude: -70.5580,
    hours: 'Lunes a Sábado 8:00 - 20:00',
    services: ['Traumatología Deportiva', 'Kinesiología', 'Cirugía Ortopédica', 'Medicina Deportiva', 'Rehabilitación'],
    description: 'Clínica especializada en medicina deportiva y traumatología.',
    urgencia: false,
    googleRating: 4.4,
    googleReviews: 6120,
    attendanceRate: '~600 pacientes/día',
  },
  {
    id: 'cp-10',
    name: 'Clínica Tabancura',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Tabancura 1185, Vitacura',
    comuna: 'Vitacura',
    phone: '+56 2 2210 7000',
    latitude: -33.3930,
    longitude: -70.5770,
    hours: '24 horas',
    services: ['Urgencia', 'Maternidad', 'Pediatría', 'Ginecología', 'Traumatología'],
    description: 'Clínica del grupo Red de Salud UC CHRISTUS con énfasis en maternidad.',
    urgencia: true,
    googleRating: 4.0,
    googleReviews: 3210,
    attendanceRate: '~800 pacientes/día',
  },
  {
    id: 'cp-11',
    name: 'Clínica RedSalud Providencia',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Salvador 130, Providencia',
    comuna: 'Providencia',
    phone: '+56 2 2592 5000',
    latitude: -33.4370,
    longitude: -70.6240,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía Ambulatoria', 'Ginecología', 'Dermatología', 'Laboratorio'],
    description: 'Centro de salud RedSalud con atención integral en Providencia.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 2670,
    attendanceRate: '~680 pacientes/día',
  },
  {
    id: 'cp-12',
    name: 'Clínica Dávila Vespucio',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Vicuña Mackenna 6570, La Florida',
    comuna: 'La Florida',
    phone: '+56 2 2730 9000',
    latitude: -33.5140,
    longitude: -70.5990,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'UCI'],
    description: 'Extensión de Clínica Dávila en el sector suroriente con convenios Fonasa.',
    urgencia: true,
    googleRating: 3.9,
    googleReviews: 4180,
    attendanceRate: '~1.150 pacientes/día',
  },
  {
    id: 'cp-13',
    name: 'Clínica Bupa Santiago',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Manuel Montt 115, Providencia',
    comuna: 'Providencia',
    phone: '+56 2 2366 7000',
    latitude: -33.4310,
    longitude: -70.6200,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía', 'Cardiología', 'Ginecología', 'Traumatología'],
    description: 'Parte de la red internacional Bupa con estándares globales.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 3450,
    attendanceRate: '~950 pacientes/día',
  },
  {
    id: 'cp-14',
    name: 'Clínica RedSalud Ñuñoa',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'José Domingo Cañas 2183, Ñuñoa',
    comuna: 'Ñuñoa',
    phone: '+56 2 2362 0800',
    latitude: -33.4520,
    longitude: -70.6020,
    hours: 'Lunes a Sábado 8:00 - 20:00',
    services: ['Medicina General', 'Ginecología', 'Dermatología', 'Oftalmología', 'Laboratorio'],
    description: 'Centro médico RedSalud en Ñuñoa con múltiples especialidades.',
    urgencia: false,
    googleRating: 3.6,
    googleReviews: 1890,
    attendanceRate: '~500 pacientes/día',
  },
  {
    id: 'cp-15',
    name: 'Clínica RedSalud Maipú',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Pajaritos 3195, Maipú',
    comuna: 'Maipú',
    phone: '+56 2 2822 0700',
    latitude: -33.5070,
    longitude: -70.7600,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Centro médico del sector poniente con convenios múltiples.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 2140,
    attendanceRate: '~700 pacientes/día',
  },
  {
    id: 'cp-16',
    name: 'Clínica RedSalud Vitacura',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Kennedy 7120, Vitacura',
    comuna: 'Vitacura',
    phone: '+56 2 2366 9000',
    latitude: -33.3940,
    longitude: -70.5740,
    hours: '24 horas',
    services: ['Urgencia', 'Cirugía', 'Cardiología', 'Oncología', 'Traumatología', 'Imagenología'],
    description: 'Clínica del sector oriente de Santiago con tecnología de punta.',
    urgencia: true,
    googleRating: 4.0,
    googleReviews: 2780,
    attendanceRate: '~900 pacientes/día',
  },

  // ═══════════════════════════════════════
  // CESFAM (20)
  // ═══════════════════════════════════════
  {
    id: 'ces-01',
    name: 'CESFAM Nº1 Ramón Corbalán Melgarejo',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Portugal 205, Santiago',
    comuna: 'Santiago',
    phone: '+56 2 2639 4920',
    latitude: -33.4480,
    longitude: -70.6380,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Vacunación'],
    description: 'Centro de salud familiar en Santiago Centro con atención primaria integral.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 1240,
    attendanceRate: '~350 pacientes/día',
  },
  {
    id: 'ces-02',
    name: 'CESFAM Cristo Vive',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Recoleta 3601, Recoleta',
    comuna: 'Recoleta',
    phone: '+56 2 2621 7880',
    latitude: -33.4100,
    longitude: -70.6420,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Medicina Complementaria', 'Salud Mental'],
    description: 'Centro de salud con enfoque intercultural y atención a población migrante.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 890,
    attendanceRate: '~320 pacientes/día',
  },
  {
    id: 'ces-03',
    name: 'CESFAM Lo Barnechea',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Camino El Alba 10765, Lo Barnechea',
    comuna: 'Lo Barnechea',
    phone: '+56 2 2216 8700',
    latitude: -33.3550,
    longitude: -70.5200,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Vacunación'],
    description: 'Centro de salud familiar que atiende a la comunidad de Lo Barnechea.',
    urgencia: false,
    googleRating: 3.6,
    googleReviews: 640,
    attendanceRate: '~280 pacientes/día',
  },
  {
    id: 'ces-04',
    name: 'CESFAM Padre Gerardo Whelan',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'José Joaquín Pérez 8630, Cerro Navia',
    comuna: 'Cerro Navia',
    phone: '+56 2 2640 1250',
    latitude: -33.4260,
    longitude: -70.7380,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Nutrición'],
    description: 'CESFAM comunitario en Cerro Navia con fuerte enfoque en salud familiar.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 710,
    attendanceRate: '~400 pacientes/día',
  },
  {
    id: 'ces-05',
    name: 'CESFAM San Alberto Hurtado',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Concha y Toro 1820, Puente Alto',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 6300',
    latitude: -33.5700,
    longitude: -70.5850,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Programa Cardiovascular', 'Salud Mental'],
    description: 'Centro de salud familiar en Puente Alto para una de las comunas más pobladas.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 980,
    attendanceRate: '~450 pacientes/día',
  },
  {
    id: 'ces-06',
    name: 'CESFAM Carol Urzúa Ibáñez',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Lo Ovalle 1650, Pedro Aguirre Cerda',
    comuna: 'Pedro Aguirre Cerda',
    phone: '+56 2 2556 2100',
    latitude: -33.4830,
    longitude: -70.6640,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Nutrición'],
    description: 'Centro de salud familiar con énfasis en salud materno-infantil.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 560,
    attendanceRate: '~310 pacientes/día',
  },
  {
    id: 'ces-07',
    name: 'CESFAM Lo Hermida',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'San Luis de Macul 2664, Peñalolén',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 5500',
    latitude: -33.4780,
    longitude: -70.5530,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Podología'],
    description: 'Centro de salud comunitario en Peñalolén.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 830,
    attendanceRate: '~370 pacientes/día',
  },
  {
    id: 'ces-08',
    name: 'CESFAM Juan Antonio Ríos',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'El Guanaco 1331, Independencia',
    comuna: 'Independencia',
    phone: '+56 2 2737 3200',
    latitude: -33.4080,
    longitude: -70.6600,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Vacunación'],
    description: 'CESFAM en Independencia con programas preventivos.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 620,
    attendanceRate: '~340 pacientes/día',
  },
  {
    id: 'ces-09',
    name: 'CESFAM Bellavista de La Florida',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Trinidad Oriente 57, La Florida',
    comuna: 'La Florida',
    phone: '+56 2 2281 1900',
    latitude: -33.5250,
    longitude: -70.5930,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Nutrición'],
    description: 'Centro de salud en La Florida con programas de vida saludable.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 740,
    attendanceRate: '~380 pacientes/día',
  },
  {
    id: 'ces-10',
    name: 'CESFAM El Roble',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Santa Rosa 12850, La Pintana',
    comuna: 'La Pintana',
    phone: '+56 2 2542 7800',
    latitude: -33.5600,
    longitude: -70.6340,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental'],
    description: 'CESFAM de La Pintana con programas de salud comunitaria.',
    urgencia: false,
    googleRating: 2.7,
    googleReviews: 510,
    attendanceRate: '~420 pacientes/día',
  },
  {
    id: 'ces-11',
    name: 'CESFAM Salvador Bustos',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Irarrázaval 4054, Ñuñoa',
    comuna: 'Ñuñoa',
    phone: '+56 2 2239 4500',
    latitude: -33.4540,
    longitude: -70.6010,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Kinesiología'],
    description: 'Centro de salud familiar de Ñuñoa con enfoque preventivo.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 920,
    attendanceRate: '~330 pacientes/día',
  },
  {
    id: 'ces-12',
    name: 'CESFAM Dr. Víctor Manuel Fernández',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Los Pajaritos 3391, Maipú',
    comuna: 'Maipú',
    phone: '+56 2 2531 8200',
    latitude: -33.5090,
    longitude: -70.7640,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Nutrición', 'Vacunación'],
    description: 'CESFAM de Maipú para el sector poniente.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 1120,
    attendanceRate: '~480 pacientes/día',
  },
  {
    id: 'ces-13',
    name: 'CESFAM Quilicura',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'San Martín 540, Quilicura',
    comuna: 'Quilicura',
    phone: '+56 2 2948 3600',
    latitude: -33.3630,
    longitude: -70.7340,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Vacunación'],
    description: 'Centro de salud de Quilicura con atención intercultural.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 680,
    attendanceRate: '~410 pacientes/día',
  },
  {
    id: 'ces-14',
    name: 'CESFAM La Reina',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Príncipe de Gales 6832, La Reina',
    comuna: 'La Reina',
    phone: '+56 2 2273 6100',
    latitude: -33.4490,
    longitude: -70.5450,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Nutrición', 'Kinesiología'],
    description: 'Centro de salud familiar de La Reina con enfoque preventivo.',
    urgencia: false,
    googleRating: 3.6,
    googleReviews: 530,
    attendanceRate: '~260 pacientes/día',
  },
  {
    id: 'ces-15',
    name: 'CESFAM Dr. Alberto Allende Jones',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Macul 3450, Macul',
    comuna: 'Macul',
    phone: '+56 2 2238 9200',
    latitude: -33.4740,
    longitude: -70.5940,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental'],
    description: 'CESFAM de Macul con fuerte vínculo comunitario.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 470,
    attendanceRate: '~290 pacientes/día',
  },
  {
    id: 'ces-16',
    name: 'CESFAM Conchalí',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Juanita Aguirre 1629, Conchalí',
    comuna: 'Conchalí',
    phone: '+56 2 2713 3200',
    latitude: -33.3890,
    longitude: -70.6530,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Vacunación'],
    description: 'Centro de salud familiar de Conchalí.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 540,
    attendanceRate: '~350 pacientes/día',
  },
  {
    id: 'ces-17',
    name: 'CESFAM Huechuraba',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Pedro Fontova 8585, Huechuraba',
    comuna: 'Huechuraba',
    phone: '+56 2 2624 5100',
    latitude: -33.3650,
    longitude: -70.6360,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Nutrición'],
    description: 'CESFAM de Huechuraba con atención integral.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 430,
    attendanceRate: '~300 pacientes/día',
  },
  {
    id: 'ces-18',
    name: 'CESFAM La Cisterna',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'El Parrón 725, La Cisterna',
    comuna: 'La Cisterna',
    phone: '+56 2 2558 4000',
    latitude: -33.5330,
    longitude: -70.6620,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental'],
    description: 'Centro de salud familiar de La Cisterna.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 480,
    attendanceRate: '~320 pacientes/día',
  },
  {
    id: 'ces-19',
    name: 'CESFAM Lo Espejo',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Clotario Blest 501, Lo Espejo',
    comuna: 'Lo Espejo',
    phone: '+56 2 2568 3200',
    latitude: -33.5190,
    longitude: -70.6880,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Vacunación'],
    description: 'CESFAM de Lo Espejo con atención primaria integral.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 370,
    attendanceRate: '~340 pacientes/día',
  },
  {
    id: 'ces-20',
    name: 'CESFAM Renca',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Domingo Santa María 3360, Renca',
    comuna: 'Renca',
    phone: '+56 2 2641 2500',
    latitude: -33.4040,
    longitude: -70.7190,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Kinesiología'],
    description: 'Centro de salud familiar de Renca.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 410,
    attendanceRate: '~360 pacientes/día',
  },

  // ═══════════════════════════════════════
  // SAPU (22)
  // ═══════════════════════════════════════
  {
    id: 'sapu-01',
    name: 'SAPU Santiago Centro',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Portugal 205, Santiago',
    comuna: 'Santiago',
    phone: '+56 2 2639 4925',
    latitude: -33.4483,
    longitude: -70.6375,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores'],
    description: 'SAPU adosado al CESFAM Nº1 de Santiago Centro.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 620,
    attendanceRate: '~180 pac/noche',
  },
  {
    id: 'sapu-02',
    name: 'SAPU Conchalí',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Juanita Aguirre 1629, Conchalí',
    comuna: 'Conchalí',
    phone: '+56 2 2713 3500',
    latitude: -33.3895,
    longitude: -70.6535,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Derivación'],
    description: 'SAPU de Conchalí para urgencias primarias fuera de horario.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 430,
    attendanceRate: '~150 pac/noche',
  },
  {
    id: 'sapu-03',
    name: 'SAPU El Bosque',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Gran Avenida 9530, El Bosque',
    comuna: 'El Bosque',
    phone: '+56 2 2528 7100',
    latitude: -33.5460,
    longitude: -70.6580,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores'],
    description: 'Servicio de urgencia primaria de El Bosque.',
    urgencia: true,
    googleRating: 2.7,
    googleReviews: 520,
    attendanceRate: '~200 pac/noche',
  },
  {
    id: 'sapu-04',
    name: 'SAPU Estación Central',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Padre Vicente Irarrázaval 3865, Estación Central',
    comuna: 'Estación Central',
    phone: '+56 2 2779 3200',
    latitude: -33.4530,
    longitude: -70.6940,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Derivación Hospitalaria'],
    description: 'SAPU de Estación Central para el sector centro-poniente.',
    urgencia: true,
    googleRating: 2.6,
    googleReviews: 390,
    attendanceRate: '~170 pac/noche',
  },
  {
    id: 'sapu-05',
    name: 'SAPU Huechuraba',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Pedro Fontova 8585, Huechuraba',
    comuna: 'Huechuraba',
    phone: '+56 2 2624 5300',
    latitude: -33.3655,
    longitude: -70.6365,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Derivación'],
    description: 'SAPU de Huechuraba para urgencias nocturnas y de fin de semana.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 310,
    attendanceRate: '~130 pac/noche',
  },
  {
    id: 'sapu-06',
    name: 'SAPU La Cisterna',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'El Parrón 725, La Cisterna',
    comuna: 'La Cisterna',
    phone: '+56 2 2558 4100',
    latitude: -33.5335,
    longitude: -70.6625,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Estabilización'],
    description: 'SAPU de La Cisterna.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 370,
    attendanceRate: '~160 pac/noche',
  },
  {
    id: 'sapu-07',
    name: 'SAPU La Granja',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'San Gregorio 8290, La Granja',
    comuna: 'La Granja',
    phone: '+56 2 2522 8500',
    latitude: -33.5310,
    longitude: -70.6240,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Suturas Menores', 'Derivación'],
    description: 'SAPU de La Granja.',
    urgencia: true,
    googleRating: 2.5,
    googleReviews: 480,
    attendanceRate: '~210 pac/noche',
  },
  {
    id: 'sapu-08',
    name: 'SAPU Lo Espejo',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Clotario Blest 501, Lo Espejo',
    comuna: 'Lo Espejo',
    phone: '+56 2 2568 3400',
    latitude: -33.5195,
    longitude: -70.6885,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Derivación'],
    description: 'SAPU de Lo Espejo.',
    urgencia: true,
    googleRating: 2.6,
    googleReviews: 290,
    attendanceRate: '~140 pac/noche',
  },
  {
    id: 'sapu-09',
    name: 'SAPU Lo Prado',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'San Pablo 5800, Lo Prado',
    comuna: 'Lo Prado',
    phone: '+56 2 2774 2100',
    latitude: -33.4430,
    longitude: -70.7250,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Suturas Menores', 'Estabilización'],
    description: 'SAPU de Lo Prado para el sector poniente.',
    urgencia: true,
    googleRating: 2.7,
    googleReviews: 340,
    attendanceRate: '~155 pac/noche',
  },
  {
    id: 'sapu-10',
    name: 'SAPU Pudahuel',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'La Estrella 401, Pudahuel',
    comuna: 'Pudahuel',
    phone: '+56 2 2749 5200',
    latitude: -33.4420,
    longitude: -70.7530,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Derivación'],
    description: 'SAPU de Pudahuel.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 410,
    attendanceRate: '~185 pac/noche',
  },
  {
    id: 'sapu-11',
    name: 'SAPU Quinta Normal',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Carrascal 3550, Quinta Normal',
    comuna: 'Quinta Normal',
    phone: '+56 2 2774 1600',
    latitude: -33.4310,
    longitude: -70.7020,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Suturas Menores', 'Derivación'],
    description: 'SAPU de Quinta Normal.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 350,
    attendanceRate: '~165 pac/noche',
  },
  {
    id: 'sapu-12',
    name: 'SAPU Renca',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Domingo Santa María 3550, Renca',
    comuna: 'Renca',
    phone: '+56 2 2641 2800',
    latitude: -33.4045,
    longitude: -70.7195,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Estabilización'],
    description: 'SAPU de Renca.',
    urgencia: true,
    googleRating: 2.7,
    googleReviews: 290,
    attendanceRate: '~145 pac/noche',
  },
  {
    id: 'sapu-13',
    name: 'SAPU San Joaquín',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Santa Rosa 3830, San Joaquín',
    comuna: 'San Joaquín',
    phone: '+56 2 2556 8700',
    latitude: -33.4940,
    longitude: -70.6280,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Suturas Menores', 'Derivación'],
    description: 'SAPU de San Joaquín.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 380,
    attendanceRate: '~175 pac/noche',
  },
  {
    id: 'sapu-14',
    name: 'SAPU Cerrillos',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Pedro Aguirre Cerda 6500, Cerrillos',
    comuna: 'Cerrillos',
    phone: '+56 2 2557 4300',
    latitude: -33.4960,
    longitude: -70.7120,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Derivación'],
    description: 'SAPU de Cerrillos.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 260,
    attendanceRate: '~120 pac/noche',
  },
  {
    id: 'sapu-15',
    name: 'SAPU San Ramón',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Santa Rosa 8750, San Ramón',
    comuna: 'San Ramón',
    phone: '+56 2 2522 9100',
    latitude: -33.5380,
    longitude: -70.6420,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Estabilización'],
    description: 'SAPU de San Ramón.',
    urgencia: true,
    googleRating: 2.6,
    googleReviews: 350,
    attendanceRate: '~190 pac/noche',
  },
  {
    id: 'sapu-16',
    name: 'SAPU Colina',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Cristóbal Colón 101, Colina',
    comuna: 'Colina',
    phone: '+56 2 2844 7500',
    latitude: -33.2025,
    longitude: -70.6715,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Derivación'],
    description: 'SAPU de Colina.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 280,
    attendanceRate: '~130 pac/noche',
  },
  {
    id: 'sapu-17',
    name: 'SAPU Lampa',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'José Manuel Balmaceda 300, Lampa',
    comuna: 'Lampa',
    phone: '+56 2 2595 3800',
    latitude: -33.2860,
    longitude: -70.8770,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Derivación Hospitalaria'],
    description: 'SAPU de Lampa.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 210,
    attendanceRate: '~100 pac/noche',
  },
  {
    id: 'sapu-18',
    name: 'SAPU Buin',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Maipú 1001, Buin',
    comuna: 'Buin',
    phone: '+56 2 2821 3400',
    latitude: -33.7315,
    longitude: -70.7425,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Estabilización'],
    description: 'SAPU de Buin.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 190,
    attendanceRate: '~90 pac/noche',
  },
  {
    id: 'sapu-19',
    name: 'SAPU Talagante',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Balmaceda 1458, Talagante',
    comuna: 'Talagante',
    phone: '+56 2 2815 7200',
    latitude: -33.6635,
    longitude: -70.9265,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Derivación'],
    description: 'SAPU de Talagante.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 170,
    attendanceRate: '~85 pac/noche',
  },
  {
    id: 'sapu-20',
    name: 'SAPU Melipilla',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Ortúzar 201, Melipilla',
    comuna: 'Melipilla',
    phone: '+56 2 2832 1500',
    latitude: -33.6865,
    longitude: -71.2135,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Derivación Hospitalaria'],
    description: 'SAPU de Melipilla.',
    urgencia: true,
    googleRating: 2.7,
    googleReviews: 240,
    attendanceRate: '~110 pac/noche',
  },
  {
    id: 'sapu-21',
    name: 'SAPU Padre Hurtado',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Camilo Henríquez 455, Padre Hurtado',
    comuna: 'Padre Hurtado',
    phone: '+56 2 2811 4000',
    latitude: -33.5710,
    longitude: -70.8280,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Derivación'],
    description: 'SAPU de Padre Hurtado.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 160,
    attendanceRate: '~80 pac/noche',
  },
  {
    id: 'sapu-22',
    name: 'SAPU Paine',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Arturo Prat 280, Paine',
    comuna: 'Paine',
    phone: '+56 2 2824 5000',
    latitude: -33.8090,
    longitude: -70.7410,
    hours: 'Lun-Vie 17:00-8:00, Sáb-Dom-Fest 24h',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Derivación'],
    description: 'SAPU de Paine.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 130,
    attendanceRate: '~70 pac/noche',
  },

  // ═══════════════════════════════════════
  // SAR (14)
  // ═══════════════════════════════════════
  {
    id: 'sar-01',
    name: 'SAR Maipú',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Tres Poniente 1155, Maipú',
    comuna: 'Maipú',
    phone: '+56 2 2571 8400',
    latitude: -33.5050,
    longitude: -70.7580,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación'],
    description: 'SAR de Maipú con capacidad de imagenología y laboratorio.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 1240,
    attendanceRate: '~350 pac/día',
  },
  {
    id: 'sar-02',
    name: 'SAR La Florida',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Walker Martínez 9500, La Florida',
    comuna: 'La Florida',
    phone: '+56 2 2576 9500',
    latitude: -33.5280,
    longitude: -70.5840,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Electrocardiograma'],
    description: 'SAR de La Florida para urgencias de mediana complejidad.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 980,
    attendanceRate: '~320 pac/día',
  },
  {
    id: 'sar-03',
    name: 'SAR Puente Alto',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Concha y Toro 2450, Puente Alto',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 6800',
    latitude: -33.5760,
    longitude: -70.5790,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación'],
    description: 'SAR de Puente Alto para descongestionar el Hospital Sótero del Río.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 1560,
    attendanceRate: '~400 pac/día',
  },
  {
    id: 'sar-04',
    name: 'SAR El Bosque',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Lo Martínez 1620, El Bosque',
    comuna: 'El Bosque',
    phone: '+56 2 2528 7500',
    latitude: -33.5510,
    longitude: -70.6630,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Electrocardiograma'],
    description: 'SAR de El Bosque del sector sur.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 870,
    attendanceRate: '~280 pac/día',
  },
  {
    id: 'sar-05',
    name: 'SAR Peñalolén',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Grecia 9250, Peñalolén',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 5800',
    latitude: -33.4810,
    longitude: -70.5430,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Estabilización Avanzada'],
    description: 'SAR de Peñalolén.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 720,
    attendanceRate: '~250 pac/día',
  },
  {
    id: 'sar-06',
    name: 'SAR San Bernardo',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Colón 1480, San Bernardo',
    comuna: 'San Bernardo',
    phone: '+56 2 2488 6500',
    latitude: -33.5950,
    longitude: -70.7010,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Electrocardiograma'],
    description: 'SAR de San Bernardo.',
    urgencia: true,
    googleRating: 3.2,
    googleReviews: 650,
    attendanceRate: '~270 pac/día',
  },
  {
    id: 'sar-07',
    name: 'SAR Quilicura',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Lo Marcoleta 830, Quilicura',
    comuna: 'Quilicura',
    phone: '+56 2 2948 3900',
    latitude: -33.3580,
    longitude: -70.7300,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación'],
    description: 'SAR de Quilicura.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 540,
    attendanceRate: '~230 pac/día',
  },
  {
    id: 'sar-08',
    name: 'SAR La Pintana',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Santa Rosa 12300, La Pintana',
    comuna: 'La Pintana',
    phone: '+56 2 2542 7900',
    latitude: -33.5570,
    longitude: -70.6310,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Estabilización'],
    description: 'SAR de La Pintana.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 610,
    attendanceRate: '~290 pac/día',
  },
  {
    id: 'sar-09',
    name: 'SAR Pudahuel',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'La Estrella 920, Pudahuel',
    comuna: 'Pudahuel',
    phone: '+56 2 2749 5500',
    latitude: -33.4400,
    longitude: -70.7580,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Electrocardiograma'],
    description: 'SAR de Pudahuel.',
    urgencia: true,
    googleRating: 3.2,
    googleReviews: 430,
    attendanceRate: '~200 pac/día',
  },
  {
    id: 'sar-10',
    name: 'SAR Conchalí',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Independencia 4600, Conchalí',
    comuna: 'Conchalí',
    phone: '+56 2 2713 3700',
    latitude: -33.3860,
    longitude: -70.6560,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Nebulizaciones'],
    description: 'SAR de Conchalí.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 480,
    attendanceRate: '~220 pac/día',
  },
  {
    id: 'sar-11',
    name: 'SAR Padre Hurtado',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Camilo Henríquez 455, Padre Hurtado',
    comuna: 'Padre Hurtado',
    phone: '+56 2 2811 4200',
    latitude: -33.5715,
    longitude: -70.8285,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación'],
    description: 'SAR de Padre Hurtado.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 320,
    attendanceRate: '~180 pac/día',
  },
  {
    id: 'sar-12',
    name: 'SAR Colina',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Cristóbal Colón 250, Colina',
    comuna: 'Colina',
    phone: '+56 2 2844 7800',
    latitude: -33.2015,
    longitude: -70.6750,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Electrocardiograma'],
    description: 'SAR de Colina.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 390,
    attendanceRate: '~190 pac/día',
  },
  {
    id: 'sar-13',
    name: 'SAR Cerro Navia',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'José Joaquín Pérez 8100, Cerro Navia',
    comuna: 'Cerro Navia',
    phone: '+56 2 2640 1800',
    latitude: -33.4265,
    longitude: -70.7360,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Estabilización'],
    description: 'SAR de Cerro Navia.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 340,
    attendanceRate: '~210 pac/día',
  },
  {
    id: 'sar-14',
    name: 'SAR San Pedro',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Melipilla 500, San Pedro',
    comuna: 'San Pedro',
    phone: '+56 2 2832 3000',
    latitude: -33.8930,
    longitude: -71.4540,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación'],
    description: 'SAR de San Pedro, provincia de Melipilla.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 180,
    attendanceRate: '~100 pac/día',
  },

  // ═══════════════════════════════════════
  // COSAM (16)
  // ═══════════════════════════════════════
  {
    id: 'cosam-01',
    name: 'COSAM Santiago',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Matta 1028, Santiago',
    comuna: 'Santiago',
    phone: '+56 2 2555 3100',
    latitude: -33.4560,
    longitude: -70.6430,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Trabajo Social', 'Rehabilitación Psicosocial'],
    description: 'Centro de salud mental comunitario de Santiago Centro.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 520,
    attendanceRate: '~120 pac/día',
  },
  {
    id: 'cosam-02',
    name: 'COSAM Pudahuel',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'La Estrella 1130, Pudahuel',
    comuna: 'Pudahuel',
    phone: '+56 2 2749 6100',
    latitude: -33.4380,
    longitude: -70.7560,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Programa de Drogas y Alcohol'],
    description: 'COSAM de Pudahuel con programas de prevención.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 340,
    attendanceRate: '~100 pac/día',
  },
  {
    id: 'cosam-03',
    name: 'COSAM Peñalolén',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Los Presidentes 8920, Peñalolén',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 6100',
    latitude: -33.4830,
    longitude: -70.5470,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología Infanto-Juvenil', 'Terapia Ocupacional', 'Programa SENDA'],
    description: 'COSAM de Peñalolén con enfoque infanto-juvenil.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 410,
    attendanceRate: '~110 pac/día',
  },
  {
    id: 'cosam-04',
    name: 'COSAM La Florida',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Walker Martínez 5645, La Florida',
    comuna: 'La Florida',
    phone: '+56 2 2281 2200',
    latitude: -33.5170,
    longitude: -70.5900,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Programa de Adicciones'],
    description: 'COSAM de La Florida.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 560,
    attendanceRate: '~130 pac/día',
  },
  {
    id: 'cosam-05',
    name: 'COSAM Maipú',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: '5 de Abril 2750, Maipú',
    comuna: 'Maipú',
    phone: '+56 2 2531 8600',
    latitude: -33.5110,
    longitude: -70.7520,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Rehabilitación Psicosocial'],
    description: 'COSAM de Maipú.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 470,
    attendanceRate: '~125 pac/día',
  },
  {
    id: 'cosam-06',
    name: 'COSAM Puente Alto',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Tocornal 130, Puente Alto',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 6900',
    latitude: -33.6090,
    longitude: -70.5790,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Programa Infanto-Juvenil', 'Programa SENDA'],
    description: 'COSAM de Puente Alto.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 640,
    attendanceRate: '~140 pac/día',
  },
  {
    id: 'cosam-07',
    name: 'COSAM San Bernardo',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Colón 1350, San Bernardo',
    comuna: 'San Bernardo',
    phone: '+56 2 2488 6800',
    latitude: -33.5910,
    longitude: -70.7030,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia de Grupo', 'Programa de Adicciones'],
    description: 'COSAM de San Bernardo.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 380,
    attendanceRate: '~105 pac/día',
  },
  {
    id: 'cosam-08',
    name: 'COSAM Ñuñoa',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'José Domingo Cañas 2590, Ñuñoa',
    comuna: 'Ñuñoa',
    phone: '+56 2 2239 4800',
    latitude: -33.4530,
    longitude: -70.6050,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Talleres Terapéuticos'],
    description: 'COSAM de Ñuñoa.',
    urgencia: false,
    googleRating: 3.7,
    googleReviews: 320,
    attendanceRate: '~95 pac/día',
  },
  {
    id: 'cosam-09',
    name: 'COSAM Recoleta',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'El Salto 2980, Recoleta',
    comuna: 'Recoleta',
    phone: '+56 2 2621 8200',
    latitude: -33.4060,
    longitude: -70.6330,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Intercultural', 'Programa de Adicciones'],
    description: 'COSAM de Recoleta con atención intercultural.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 290,
    attendanceRate: '~100 pac/día',
  },
  {
    id: 'cosam-10',
    name: 'COSAM El Bosque',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Lo Martínez 1300, El Bosque',
    comuna: 'El Bosque',
    phone: '+56 2 2528 7300',
    latitude: -33.5480,
    longitude: -70.6610,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Programa de Drogas'],
    description: 'COSAM de El Bosque.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 250,
    attendanceRate: '~90 pac/día',
  },
  {
    id: 'cosam-11',
    name: 'COSAM Estación Central',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Ecuador 4140, Estación Central',
    comuna: 'Estación Central',
    phone: '+56 2 2779 3400',
    latitude: -33.4510,
    longitude: -70.6980,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Programa de Adicciones'],
    description: 'COSAM de Estación Central.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 270,
    attendanceRate: '~85 pac/día',
  },
  {
    id: 'cosam-12',
    name: 'COSAM Independencia',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Vivaceta 1630, Independencia',
    comuna: 'Independencia',
    phone: '+56 2 2737 3400',
    latitude: -33.4110,
    longitude: -70.6650,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Rehabilitación Psicosocial', 'Programa SENDA'],
    description: 'COSAM de Independencia.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 230,
    attendanceRate: '~80 pac/día',
  },
  {
    id: 'cosam-13',
    name: 'COSAM La Pintana',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Santa Rosa 13100, La Pintana',
    comuna: 'La Pintana',
    phone: '+56 2 2542 8100',
    latitude: -33.5630,
    longitude: -70.6370,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Programa de Adicciones'],
    description: 'COSAM de La Pintana.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 310,
    attendanceRate: '~110 pac/día',
  },
  {
    id: 'cosam-14',
    name: 'COSAM Quilicura',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Lo Marcoleta 660, Quilicura',
    comuna: 'Quilicura',
    phone: '+56 2 2948 4100',
    latitude: -33.3600,
    longitude: -70.7320,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Intercultural', 'Programa Infanto-Juvenil'],
    description: 'COSAM de Quilicura con atención intercultural.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 280,
    attendanceRate: '~90 pac/día',
  },
  {
    id: 'cosam-15',
    name: 'COSAM Cerro Navia',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'José Joaquín Pérez 8300, Cerro Navia',
    comuna: 'Cerro Navia',
    phone: '+56 2 2640 1500',
    latitude: -33.4280,
    longitude: -70.7350,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Programa de Drogas y Alcohol', 'Talleres'],
    description: 'COSAM de Cerro Navia.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 190,
    attendanceRate: '~85 pac/día',
  },
  {
    id: 'cosam-16',
    name: 'COSAM San Miguel',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Departamental 240, San Miguel',
    comuna: 'San Miguel',
    phone: '+56 2 2556 9200',
    latitude: -33.4950,
    longitude: -70.6510,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Rehabilitación Psicosocial'],
    description: 'COSAM de San Miguel.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 260,
    attendanceRate: '~95 pac/día',
  },

  // ═══════════════════════════════════════
  // CECOF (18)
  // ═══════════════════════════════════════
  {
    id: 'cecof-01',
    name: 'CECOF Villa Portales',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Las Encinas 3490, Estación Central',
    comuna: 'Estación Central',
    phone: '+56 2 2779 3500',
    latitude: -33.4560,
    longitude: -70.6910,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Programa de Crónicos', 'Talleres de Salud'],
    description: 'CECOF de Estación Central.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 180,
    attendanceRate: '~80 pac/día',
  },
  {
    id: 'cecof-02',
    name: 'CECOF Lo Hermida',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Grecia 8550, Peñalolén',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 5600',
    latitude: -33.4760,
    longitude: -70.5550,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Visitas Domiciliarias'],
    description: 'CECOF de Peñalolén.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 150,
    attendanceRate: '~70 pac/día',
  },
  {
    id: 'cecof-03',
    name: 'CECOF Villa O Higgins',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Santa Rosa 9100, La Granja',
    comuna: 'La Granja',
    phone: '+56 2 2522 8700',
    latitude: -33.5350,
    longitude: -70.6200,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Programa de Crónicos', 'Talleres'],
    description: 'CECOF de La Granja.',
    urgencia: false,
    googleRating: 2.7,
    googleReviews: 130,
    attendanceRate: '~65 pac/día',
  },
  {
    id: 'cecof-04',
    name: 'CECOF San Joaquín Sur',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Vicuña Mackenna 5100, San Joaquín',
    comuna: 'San Joaquín',
    phone: '+56 2 2556 8900',
    latitude: -33.4980,
    longitude: -70.6250,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Visitas Domiciliarias'],
    description: 'CECOF de San Joaquín.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 140,
    attendanceRate: '~60 pac/día',
  },
  {
    id: 'cecof-05',
    name: 'CECOF Bajos de Mena',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Gabriela 3450, Puente Alto',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 7100',
    latitude: -33.6190,
    longitude: -70.5810,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Programa de Crónicos', 'Talleres Comunitarios'],
    description: 'CECOF de Bajos de Mena, Puente Alto.',
    urgencia: false,
    googleRating: 2.6,
    googleReviews: 280,
    attendanceRate: '~90 pac/día',
  },
  {
    id: 'cecof-06',
    name: 'CECOF Lo Prado Norte',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'San Pablo 5450, Lo Prado',
    comuna: 'Lo Prado',
    phone: '+56 2 2774 2300',
    latitude: -33.4410,
    longitude: -70.7200,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Visitas Domiciliarias'],
    description: 'CECOF de Lo Prado.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 120,
    attendanceRate: '~55 pac/día',
  },
  {
    id: 'cecof-07',
    name: 'CECOF Pedro Aguirre Cerda',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Club Hípico 3200, Pedro Aguirre Cerda',
    comuna: 'Pedro Aguirre Cerda',
    phone: '+56 2 2556 2300',
    latitude: -33.4810,
    longitude: -70.6700,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Programa de Crónicos', 'Curaciones'],
    description: 'CECOF de Pedro Aguirre Cerda.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 110,
    attendanceRate: '~50 pac/día',
  },
  {
    id: 'cecof-08',
    name: 'CECOF Tiltil',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Principal 450, Tiltil',
    comuna: 'Tiltil',
    phone: '+56 2 2595 4200',
    latitude: -33.0870,
    longitude: -70.9250,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Visitas Domiciliarias', 'Programa Rural'],
    description: 'CECOF de Tiltil, comuna rural.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 80,
    attendanceRate: '~35 pac/día',
  },
  {
    id: 'cecof-09',
    name: 'CECOF San José de Maipo',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Comercio 9670, San José de Maipo',
    comuna: 'San José de Maipo',
    phone: '+56 2 2861 2100',
    latitude: -33.6390,
    longitude: -70.3510,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Visitas Domiciliarias'],
    description: 'CECOF de San José de Maipo, zona cordillerana.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 90,
    attendanceRate: '~30 pac/día',
  },
  {
    id: 'cecof-10',
    name: 'CECOF Pirque',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Ramón Subercaseaux 3120, Pirque',
    comuna: 'Pirque',
    phone: '+56 2 2854 3200',
    latitude: -33.6530,
    longitude: -70.5980,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Visitas Domiciliarias'],
    description: 'CECOF de Pirque, comuna precordillerana.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 70,
    attendanceRate: '~25 pac/día',
  },
  {
    id: 'cecof-11',
    name: 'CECOF Calera de Tango',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Lonquén 8620, Calera de Tango',
    comuna: 'Calera de Tango',
    phone: '+56 2 2855 1400',
    latitude: -33.6310,
    longitude: -70.7730,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Programa de Crónicos', 'Talleres'],
    description: 'CECOF de Calera de Tango.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 60,
    attendanceRate: '~25 pac/día',
  },
  {
    id: 'cecof-12',
    name: 'CECOF Paine',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Arturo Prat 280, Paine',
    comuna: 'Paine',
    phone: '+56 2 2824 5100',
    latitude: -33.8090,
    longitude: -70.7410,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Programa Rural'],
    description: 'CECOF de Paine.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 85,
    attendanceRate: '~35 pac/día',
  },
  {
    id: 'cecof-13',
    name: 'CECOF Isla de Maipo',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Gonzalo Pérez 320, Isla de Maipo',
    comuna: 'Isla de Maipo',
    phone: '+56 2 2819 3500',
    latitude: -33.7470,
    longitude: -70.8900,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Visitas Domiciliarias'],
    description: 'CECOF de Isla de Maipo.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 65,
    attendanceRate: '~30 pac/día',
  },
  {
    id: 'cecof-14',
    name: 'CECOF El Monte',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: "O'Higgins 450, El Monte",
    comuna: 'El Monte',
    phone: '+56 2 2819 4200',
    latitude: -33.6840,
    longitude: -71.0100,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Programa Rural'],
    description: 'CECOF de El Monte.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 55,
    attendanceRate: '~25 pac/día',
  },
  {
    id: 'cecof-15',
    name: 'CECOF Peñaflor',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Balmaceda 1250, Peñaflor',
    comuna: 'Peñaflor',
    phone: '+56 2 2812 5800',
    latitude: -33.6120,
    longitude: -70.8780,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Talleres de Salud'],
    description: 'CECOF de Peñaflor.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 95,
    attendanceRate: '~40 pac/día',
  },
  {
    id: 'cecof-16',
    name: 'CECOF María Pinto',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Principal 180, María Pinto',
    comuna: 'María Pinto',
    phone: '+56 2 2831 2400',
    latitude: -33.5110,
    longitude: -71.1170,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Programa Rural', 'Visitas Domiciliarias'],
    description: 'CECOF de María Pinto, comuna rural.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 40,
    attendanceRate: '~20 pac/día',
  },
  {
    id: 'cecof-17',
    name: 'CECOF Curacaví',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: "Ambrosio O'Higgins 650, Curacaví",
    comuna: 'Curacaví',
    phone: '+56 2 2831 3100',
    latitude: -33.4010,
    longitude: -71.1410,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Visitas Domiciliarias'],
    description: 'CECOF de Curacaví.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 75,
    attendanceRate: '~30 pac/día',
  },
  {
    id: 'cecof-18',
    name: 'CECOF Alhué',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Villa Alhué 120, Alhué',
    comuna: 'Alhué',
    phone: '+56 2 2831 4500',
    latitude: -34.0280,
    longitude: -71.0600,
    hours: 'Lunes a Viernes 8:00 - 16:00',
    services: ['Medicina General', 'Vacunación', 'Visitas Domiciliarias', 'Programa Rural'],
    description: 'CECOF de Alhué, la comuna más austral de la RM.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 30,
    attendanceRate: '~15 pac/día',
  },

  // ═══════════════════════════════════════
  // ASEGURADORAS (12)
  // ═══════════════════════════════════════
  {
    id: 'seg-01',
    name: 'Fonasa - Santiago Centro',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Monjitas 665, Santiago',
    comuna: 'Santiago',
    phone: '+56 600 360 3000',
    latitude: -33.4380,
    longitude: -70.6480,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Programa GES/AUGE'],
    description: 'Sucursal principal de Fonasa en Santiago Centro.',
    urgencia: false,
    googleRating: 2.5,
    googleReviews: 3420,
    attendanceRate: '~500 atenciones/día',
  },
  {
    id: 'seg-02',
    name: 'Fonasa - Maipú',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Pajaritos 3195, Maipú',
    comuna: 'Maipú',
    phone: '+56 600 360 3000',
    latitude: -33.5070,
    longitude: -70.7600,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Programa GES/AUGE'],
    description: 'Sucursal de Fonasa en Maipú.',
    urgencia: false,
    googleRating: 2.4,
    googleReviews: 1890,
    attendanceRate: '~350 atenciones/día',
  },
  {
    id: 'seg-03',
    name: 'Fonasa - Puente Alto',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Concha y Toro 60, Puente Alto',
    comuna: 'Puente Alto',
    phone: '+56 600 360 3000',
    latitude: -33.6110,
    longitude: -70.5760,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Programa GES/AUGE'],
    description: 'Oficina de Fonasa en Puente Alto.',
    urgencia: false,
    googleRating: 2.3,
    googleReviews: 2150,
    attendanceRate: '~400 atenciones/día',
  },
  {
    id: 'seg-04',
    name: 'Fonasa - La Florida',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Vicuña Mackenna 6100, La Florida',
    comuna: 'La Florida',
    phone: '+56 600 360 3000',
    latitude: -33.5130,
    longitude: -70.6010,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Programa GES/AUGE'],
    description: 'Sucursal de Fonasa en La Florida.',
    urgencia: false,
    googleRating: 2.6,
    googleReviews: 1670,
    attendanceRate: '~320 atenciones/día',
  },
  {
    id: 'seg-05',
    name: 'Fonasa - San Bernardo',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Colón 580, San Bernardo',
    comuna: 'San Bernardo',
    phone: '+56 600 360 3000',
    latitude: -33.5930,
    longitude: -70.6990,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Programa GES/AUGE'],
    description: 'Oficina de Fonasa en San Bernardo.',
    urgencia: false,
    googleRating: 2.5,
    googleReviews: 1230,
    attendanceRate: '~280 atenciones/día',
  },
  {
    id: 'seg-06',
    name: 'Isapre Banmédica',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Apoquindo 3600, Las Condes',
    comuna: 'Las Condes',
    phone: '+56 600 600 3600',
    latitude: -33.4170,
    longitude: -70.5960,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Programa GES'],
    description: 'Isapre Banmédica, aseguradora privada líder.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 2340,
    attendanceRate: '~200 atenciones/día',
  },
  {
    id: 'seg-07',
    name: 'Isapre Colmena',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Providencia 1909, Providencia',
    comuna: 'Providencia',
    phone: '+56 600 600 8100',
    latitude: -33.4320,
    longitude: -70.6130,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Programa GES'],
    description: 'Isapre Colmena Golden Cross.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 1890,
    attendanceRate: '~180 atenciones/día',
  },
  {
    id: 'seg-08',
    name: 'Isapre Cruz Blanca',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Apoquindo 4700, Las Condes',
    comuna: 'Las Condes',
    phone: '+56 600 600 2200',
    latitude: -33.4100,
    longitude: -70.5740,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Programa GES'],
    description: 'Isapre Cruz Blanca, parte del grupo Bupa.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 2670,
    attendanceRate: '~220 atenciones/día',
  },
  {
    id: 'seg-09',
    name: 'Isapre Consalud',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Huérfanos 1273, Santiago',
    comuna: 'Santiago',
    phone: '+56 600 600 2700',
    latitude: -33.4430,
    longitude: -70.6520,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Programa GES'],
    description: 'Isapre Consalud, una de las mayores de Chile.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 3120,
    attendanceRate: '~250 atenciones/día',
  },
  {
    id: 'seg-10',
    name: 'Isapre Vida Tres',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Providencia 2653, Providencia',
    comuna: 'Providencia',
    phone: '+56 600 600 8300',
    latitude: -33.4280,
    longitude: -70.6070,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Programa GES'],
    description: 'Isapre Vida Tres del grupo Banmédica.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 1450,
    attendanceRate: '~160 atenciones/día',
  },
  {
    id: 'seg-11',
    name: 'Fonasa - Melipilla',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Ortúzar 350, Melipilla',
    comuna: 'Melipilla',
    phone: '+56 600 360 3000',
    latitude: -33.6880,
    longitude: -71.2110,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Programa GES/AUGE'],
    description: 'Fonasa en Melipilla.',
    urgencia: false,
    googleRating: 2.6,
    googleReviews: 680,
    attendanceRate: '~150 atenciones/día',
  },
  {
    id: 'seg-12',
    name: 'Fonasa - Quilicura',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Manuel Antonio Matta 798, Quilicura',
    comuna: 'Quilicura',
    phone: '+56 600 360 3000',
    latitude: -33.3650,
    longitude: -70.7370,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Programa GES/AUGE'],
    description: 'Fonasa en Quilicura.',
    urgencia: false,
    googleRating: 2.4,
    googleReviews: 920,
    attendanceRate: '~230 atenciones/día',
  },

  // ═══════════════════════════════════════
  // MUTUALES DE SEGURIDAD (10)
  // ═══════════════════════════════════════
  {
    id: 'mut-01',
    name: 'ACHS - Hospital del Trabajador',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Ramón Carnicer 185, Providencia',
    comuna: 'Providencia',
    phone: '+56 600 600 2247',
    latitude: -33.4380,
    longitude: -70.6210,
    hours: '24 horas',
    services: ['Urgencia Laboral', 'Traumatología', 'Cirugía', 'Rehabilitación', 'Medicina del Trabajo', 'UCI'],
    description: 'Hospital del Trabajador de la ACHS, referente en atención de accidentes laborales.',
    urgencia: true,
    googleRating: 3.9,
    googleReviews: 5840,
    attendanceRate: '~1.500 pac/día',
  },
  {
    id: 'mut-02',
    name: 'ACHS - Agencia Santiago Centro',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Vicuña Mackenna 152, Santiago',
    comuna: 'Santiago',
    phone: '+56 600 600 2247',
    latitude: -33.4460,
    longitude: -70.6400,
    hours: 'Lunes a Viernes 8:30 - 18:00',
    services: ['Atención Accidentes Laborales', 'Evaluación Médica', 'Rehabilitación', 'Prevención de Riesgos'],
    description: 'Agencia de la ACHS en Santiago Centro.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 2340,
    attendanceRate: '~400 pac/día',
  },
  {
    id: 'mut-03',
    name: 'ACHS - Agencia Maipú',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Pajaritos 3070, Maipú',
    comuna: 'Maipú',
    phone: '+56 600 600 2247',
    latitude: -33.5060,
    longitude: -70.7590,
    hours: 'Lunes a Viernes 8:30 - 18:00',
    services: ['Atención Accidentes Laborales', 'Evaluación Médica', 'Rehabilitación', 'Prevención'],
    description: 'Agencia ACHS en Maipú.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 1120,
    attendanceRate: '~250 pac/día',
  },
  {
    id: 'mut-04',
    name: 'Mutual de Seguridad - Hospital',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'San Borja 115, Santiago',
    comuna: 'Santiago',
    phone: '+56 600 226 7000',
    latitude: -33.4490,
    longitude: -70.6530,
    hours: '24 horas',
    services: ['Urgencia Laboral', 'Traumatología', 'Cirugía', 'Rehabilitación', 'Medicina Laboral', 'UCI'],
    description: 'Hospital de la Mutual de Seguridad CChC, especializado en accidentes del trabajo.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 4560,
    attendanceRate: '~1.200 pac/día',
  },
  {
    id: 'mut-05',
    name: 'Mutual de Seguridad - Agencia Providencia',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Antonio Varas 175, Providencia',
    comuna: 'Providencia',
    phone: '+56 600 226 7000',
    latitude: -33.4350,
    longitude: -70.6150,
    hours: 'Lunes a Viernes 8:30 - 18:00',
    services: ['Atención Accidentes Laborales', 'Evaluación Médica', 'Rehabilitación', 'Prevención'],
    description: 'Agencia de la Mutual de Seguridad en Providencia.',
    urgencia: false,
    googleRating: 3.6,
    googleReviews: 1890,
    attendanceRate: '~300 pac/día',
  },
  {
    id: 'mut-06',
    name: 'Mutual de Seguridad - Agencia La Florida',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Vicuña Mackenna 7110, La Florida',
    comuna: 'La Florida',
    phone: '+56 600 226 7000',
    latitude: -33.5200,
    longitude: -70.5970,
    hours: 'Lunes a Viernes 8:30 - 18:00',
    services: ['Atención Accidentes Laborales', 'Evaluación Médica', 'Rehabilitación'],
    description: 'Agencia de la Mutual de Seguridad en La Florida.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 980,
    attendanceRate: '~200 pac/día',
  },
  {
    id: 'mut-07',
    name: 'IST - Instituto de Seguridad del Trabajo',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Huérfanos 1376, Santiago',
    comuna: 'Santiago',
    phone: '+56 600 600 1478',
    latitude: -33.4430,
    longitude: -70.6540,
    hours: 'Lunes a Viernes 8:30 - 18:00',
    services: ['Atención Accidentes Laborales', 'Evaluación Médica', 'Rehabilitación', 'Prevención de Riesgos'],
    description: 'Instituto de Seguridad del Trabajo, mutual de empleadores.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 1560,
    attendanceRate: '~350 pac/día',
  },
  {
    id: 'mut-08',
    name: 'ACHS - Agencia Puente Alto',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Concha y Toro 350, Puente Alto',
    comuna: 'Puente Alto',
    phone: '+56 600 600 2247',
    latitude: -33.6100,
    longitude: -70.5770,
    hours: 'Lunes a Viernes 8:30 - 18:00',
    services: ['Atención Accidentes Laborales', 'Evaluación Médica', 'Rehabilitación'],
    description: 'Agencia ACHS en Puente Alto.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 870,
    attendanceRate: '~200 pac/día',
  },
  {
    id: 'mut-09',
    name: 'Mutual de Seguridad - San Bernardo',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Eyzaguirre 450, San Bernardo',
    comuna: 'San Bernardo',
    phone: '+56 600 226 7000',
    latitude: -33.5920,
    longitude: -70.7000,
    hours: 'Lunes a Viernes 8:30 - 18:00',
    services: ['Atención Accidentes Laborales', 'Evaluación Médica', 'Rehabilitación'],
    description: 'Agencia de la Mutual en San Bernardo.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 640,
    attendanceRate: '~180 pac/día',
  },
  {
    id: 'mut-10',
    name: 'ACHS - Agencia Quilicura',
    type: 'mutual',
    typeLabel: 'Mutual',
    address: 'Matta 370, Quilicura',
    comuna: 'Quilicura',
    phone: '+56 600 600 2247',
    latitude: -33.3640,
    longitude: -70.7350,
    hours: 'Lunes a Viernes 8:30 - 18:00',
    services: ['Atención Accidentes Laborales', 'Evaluación Médica', 'Prevención de Riesgos'],
    description: 'Agencia ACHS en Quilicura.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 450,
    attendanceRate: '~150 pac/día',
  },
];
