export type FacilityType =
  | 'hospital_publico'
  | 'cesfam'
  | 'clinica_privada'
  | 'sapu'
  | 'sar'
  | 'cosam'
  | 'cecof'
  | 'aseguradora';

export interface Facility {
  id: string;
  name: string;
  type: FacilityType;
  typeLabel: string;
  address: string;
  comuna: string;
  phone: string;
  latitude: number;
  longitude: number;
  hours: string;
  services: string[];
  description: string;
  urgencia: boolean;
  googleRating: number;
  googleReviews: number;
  attendanceRate: string;
}

export const facilityTypeConfig: Record<
  FacilityType,
  { label: string; color: string; lightColor: string; icon: string }
> = {
  hospital_publico: {
    label: 'Hospital Público',
    color: '#DC2626',
    lightColor: '#FEE2E2',
    icon: 'local-hospital',
  },
  cesfam: {
    label: 'CESFAM',
    color: '#059669',
    lightColor: '#D1FAE5',
    icon: 'health-and-safety',
  },
  clinica_privada: {
    label: 'Clínica Privada',
    color: '#7C3AED',
    lightColor: '#EDE9FE',
    icon: 'medical-services',
  },
  sapu: {
    label: 'SAPU',
    color: '#EA580C',
    lightColor: '#FFEDD5',
    icon: 'emergency',
  },
  sar: {
    label: 'SAR',
    color: '#D97706',
    lightColor: '#FEF3C7',
    icon: 'bolt',
  },
  cosam: {
    label: 'COSAM',
    color: '#4F46E5',
    lightColor: '#E0E7FF',
    icon: 'psychology',
  },
  cecof: {
    label: 'CECOF',
    color: '#0891B2',
    lightColor: '#CFFAFE',
    icon: 'groups',
  },
  aseguradora: {
    label: 'Aseguradora',
    color: '#2563EB',
    lightColor: '#DBEAFE',
    icon: 'verified-user',
  },
};

export const facilities: Facility[] = [
  // ═══════════════════════════════════════
  // HOSPITALES PÚBLICOS (15)
  // ═══════════════════════════════════════
  {
    id: 'hp-01',
    name: 'Hospital San José',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. San José 1196',
    comuna: 'Independencia',
    phone: '+56 2 2568 4000',
    latitude: -33.4195,
    longitude: -70.6518,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía General', 'Pediatría', 'Ginecología y Obstetricia', 'Traumatología', 'UCI', 'Imagenología'],
    description: 'Hospital público de alta complejidad perteneciente al Servicio de Salud Metropolitano Norte. Atiende a la población de las comunas del sector norte de Santiago.',
    urgencia: true,
    googleRating: 3.2,
    googleReviews: 4823,
    attendanceRate: '~1.200 pacientes/día',
  },
  {
    id: 'hp-02',
    name: 'Hospital San Juan de Dios',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Portales 3239',
    comuna: 'Santiago',
    phone: '+56 2 2574 8000',
    latitude: -33.4510,
    longitude: -70.6820,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Neurología', 'Cardiología', 'Nefrología', 'UCI', 'Neonatología'],
    description: 'Uno de los hospitales más antiguos de Chile, ubicado en el centro de Santiago. Ofrece atención de alta complejidad para el sector occidente de la capital.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 5102,
    attendanceRate: '~1.400 pacientes/día',
  },
  {
    id: 'hp-03',
    name: 'Hospital Clínico San Borja Arriarán',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Santa Rosa 1234',
    comuna: 'Santiago',
    phone: '+56 2 2574 0100',
    latitude: -33.4505,
    longitude: -70.6478,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Dermatología', 'Oftalmología', 'UCI'],
    description: 'Hospital de alta complejidad del Servicio de Salud Metropolitano Central, ubicado en el corazón de Santiago.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 3956,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'hp-04',
    name: 'Hospital Barros Luco Trudeau',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. José Miguel Carrera 3204',
    comuna: 'San Miguel',
    phone: '+56 2 2394 8000',
    latitude: -33.4920,
    longitude: -70.6560,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Traumatología', 'Neurocirugía', 'Cardiología', 'UCI', 'Diálisis'],
    description: 'Hospital de referencia del sector sur de Santiago con amplio servicio de urgencia y especialidades de alta complejidad.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 4210,
    attendanceRate: '~1.350 pacientes/día',
  },
  {
    id: 'hp-05',
    name: 'Hospital Dr. Sótero del Río',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Concha y Toro 3459',
    comuna: 'Puente Alto',
    phone: '+56 2 2576 2600',
    latitude: -33.5830,
    longitude: -70.5750,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Maternidad', 'Traumatología', 'UCI', 'Laboratorio'],
    description: 'Principal hospital público del sector suroriente de Santiago, atendiendo a Puente Alto, La Pintana, San José de Maipo y Pirque.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 6230,
    attendanceRate: '~1.600 pacientes/día',
  },
  {
    id: 'hp-06',
    name: 'Hospital Padre Hurtado',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Esperanza 2150',
    comuna: 'San Ramón',
    phone: '+56 2 2576 7700',
    latitude: -33.5340,
    longitude: -70.6350,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Hospital de mediana complejidad que atiende a San Ramón, La Granja y La Pintana. Inaugurado en 2001.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2870,
    attendanceRate: '~850 pacientes/día',
  },
  {
    id: 'hp-07',
    name: 'Hospital El Pino',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Santiago Bueras 1003',
    comuna: 'San Bernardo',
    phone: '+56 2 2488 6000',
    latitude: -33.5920,
    longitude: -70.7050,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Laboratorio'],
    description: 'Hospital de mediana complejidad ubicado en San Bernardo, atendiendo al sector sur-poniente del área metropolitana.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 3415,
    attendanceRate: '~900 pacientes/día',
  },
  {
    id: 'hp-08',
    name: 'Hospital Félix Bulnes Cerda',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Mapocho 7432',
    comuna: 'Cerro Navia',
    phone: '+56 2 2574 5600',
    latitude: -33.4240,
    longitude: -70.7310,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'UCI Neonatal'],
    description: 'Hospital público del sector norponiente de Santiago con modernas instalaciones y tecnología de punta.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 2145,
    attendanceRate: '~950 pacientes/día',
  },
  {
    id: 'hp-09',
    name: 'Hospital de Niños Roberto del Río',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Profesor Zañartu 1085',
    comuna: 'Independencia',
    phone: '+56 2 2575 5400',
    latitude: -33.4170,
    longitude: -70.6540,
    hours: '24 horas',
    services: ['Urgencia Pediátrica', 'Pediatría', 'Cirugía Infantil', 'Neurología Infantil', 'Cardiología Infantil', 'UCI Pediátrica', 'Neonatología'],
    description: 'Principal hospital pediátrico del norte de Santiago. Centro de referencia nacional en especialidades infantiles.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 3890,
    attendanceRate: '~800 pacientes/día',
  },
  {
    id: 'hp-10',
    name: 'Hospital Dr. Exequiel González Cortés',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Ramón Barros Luco 3301',
    comuna: 'San Miguel',
    phone: '+56 2 2576 4800',
    latitude: -33.4970,
    longitude: -70.6590,
    hours: '24 horas',
    services: ['Urgencia Pediátrica', 'Pediatría', 'Cirugía Infantil', 'Traumatología Infantil', 'UCI Pediátrica', 'Odontología Infantil'],
    description: 'Hospital pediátrico de referencia del sector sur de Santiago, especializado en la atención integral de niños y adolescentes.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 2760,
    attendanceRate: '~700 pacientes/día',
  },
  {
    id: 'hp-11',
    name: 'Hospital Clínico Universidad de Chile',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Santos Dumont 999',
    comuna: 'Independencia',
    phone: '+56 2 2978 8000',
    latitude: -33.4155,
    longitude: -70.6490,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Oncología', 'Cardiología', 'Neurología', 'Trasplantes', 'UCI'],
    description: 'Hospital universitario de alta complejidad, referente nacional en docencia médica, investigación clínica y trasplantes.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 5840,
    attendanceRate: '~1.300 pacientes/día',
  },
  {
    id: 'hp-12',
    name: 'Hospital del Salvador',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Salvador 364',
    comuna: 'Providencia',
    phone: '+56 2 2575 4000',
    latitude: -33.4385,
    longitude: -70.6270,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Reumatología', 'Oftalmología', 'Dermatología', 'Geriatría', 'UCI'],
    description: 'Hospital público de alta complejidad del SSMSO, referente en reumatología y oftalmología.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 4120,
    attendanceRate: '~1.050 pacientes/día',
  },
  {
    id: 'hp-13',
    name: 'Hospital San Borja Arriarán - Complejo Asistencial',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Natalio Cox 44',
    comuna: 'Santiago',
    phone: '+56 2 2574 0200',
    latitude: -33.4470,
    longitude: -70.6530,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Traumatología', 'Cirugía Plástica', 'Quemados', 'UCI', 'Rehabilitación'],
    description: 'Centro asistencial especializado del SSMC, destacado por su unidad de grandes quemados.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 2310,
    attendanceRate: '~750 pacientes/día',
  },
  {
    id: 'hp-14',
    name: 'Hospital de La Florida',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Av. Froilán Roa 6542',
    comuna: 'La Florida',
    phone: '+56 2 2576 9000',
    latitude: -33.5200,
    longitude: -70.5980,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'UCI', 'Imagenología'],
    description: 'Hospital público de alta complejidad inaugurado en 2014, equipado con tecnología moderna para la comuna más poblada de Santiago.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 3650,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'hp-15',
    name: 'Hospital de Maipú',
    type: 'hospital_publico',
    typeLabel: 'Hospital Público',
    address: 'Camino a Rinconada 1201',
    comuna: 'Maipú',
    phone: '+56 2 2576 5000',
    latitude: -33.5100,
    longitude: -70.7570,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'Neonatología', 'UCI'],
    description: 'Hospital moderno de alta complejidad inaugurado en 2018, atiende a Maipú y Cerrillos del sector poniente.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2980,
    attendanceRate: '~1.000 pacientes/día',
  },

  // ═══════════════════════════════════════
  // CLÍNICAS PRIVADAS (15)
  // ═══════════════════════════════════════
  {
    id: 'cp-01',
    name: 'Clínica Alemana',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Vitacura 5951',
    comuna: 'Vitacura',
    phone: '+56 2 2210 1111',
    latitude: -33.3970,
    longitude: -70.5910,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Neurología', 'Imagenología', 'Laboratorio', 'UCI'],
    description: 'Una de las clínicas más prestigiosas de Chile y Sudamérica, reconocida por su excelencia médica y tecnología de vanguardia.',
    urgencia: true,
    googleRating: 4.3,
    googleReviews: 12540,
    attendanceRate: '~2.500 pacientes/día',
  },
  {
    id: 'cp-02',
    name: 'Clínica Las Condes',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Lo Fontecilla 441',
    comuna: 'Las Condes',
    phone: '+56 2 2210 4000',
    latitude: -33.4080,
    longitude: -70.5700,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía Robótica', 'Cardiología', 'Oncología', 'Neurocirugía', 'Traumatología', 'Centro de Trasplantes'],
    description: 'Clínica de alta complejidad reconocida internacionalmente por su programa de trasplantes y cirugía robótica.',
    urgencia: true,
    googleRating: 4.2,
    googleReviews: 10870,
    attendanceRate: '~2.200 pacientes/día',
  },
  {
    id: 'cp-03',
    name: 'Clínica Santa María',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Santa María 0500',
    comuna: 'Providencia',
    phone: '+56 2 2913 0000',
    latitude: -33.4220,
    longitude: -70.6180,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Maternidad', 'Pediatría', 'Cardiología', 'Traumatología', 'Imagenología'],
    description: 'Clínica de larga trayectoria en Providencia, reconocida por su servicio de maternidad y atención integral.',
    urgencia: true,
    googleRating: 4.0,
    googleReviews: 8940,
    attendanceRate: '~1.800 pacientes/día',
  },
  {
    id: 'cp-04',
    name: 'Clínica Dávila',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Recoleta 464',
    comuna: 'Recoleta',
    phone: '+56 2 2730 8000',
    latitude: -33.4290,
    longitude: -70.6420,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Neurología', 'UCI', 'Diálisis'],
    description: 'Centro de salud integral en Recoleta con amplia cobertura de especialidades y convenios Fonasa e Isapre.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 7620,
    attendanceRate: '~1.900 pacientes/día',
  },
  {
    id: 'cp-05',
    name: 'Clínica Indisa',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Santa María 1810',
    comuna: 'Providencia',
    phone: '+56 2 2362 5555',
    latitude: -33.4250,
    longitude: -70.6120,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Ginecología', 'Traumatología', 'Dermatología', 'Oftalmología'],
    description: 'Clínica en Providencia con más de 40 años de experiencia en atención médica integral.',
    urgencia: true,
    googleRating: 3.9,
    googleReviews: 5430,
    attendanceRate: '~1.200 pacientes/día',
  },
  {
    id: 'cp-06',
    name: 'Clínica Universidad de los Andes',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Plaza 2501',
    comuna: 'Las Condes',
    phone: '+56 2 2618 3000',
    latitude: -33.3850,
    longitude: -70.5490,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Cardiología', 'Imagenología', 'Laboratorio'],
    description: 'Clínica universitaria con enfoque académico y asistencial, combinando docencia, investigación y atención de excelencia.',
    urgencia: true,
    googleRating: 4.1,
    googleReviews: 4560,
    attendanceRate: '~1.100 pacientes/día',
  },
  {
    id: 'cp-07',
    name: 'Clínica Bicentenario',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Américo Vespucio Sur 501',
    comuna: 'La Florida',
    phone: '+56 2 2366 2100',
    latitude: -33.5180,
    longitude: -70.5920,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Maternidad', 'Pediatría', 'Traumatología', 'Imagenología'],
    description: 'Clínica moderna en La Florida, ofreciendo atención de calidad al sector suroriente con convenios Fonasa.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 3890,
    attendanceRate: '~1.050 pacientes/día',
  },
  {
    id: 'cp-08',
    name: 'Clínica Vespucio',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Américo Vespucio 1100',
    comuna: 'La Florida',
    phone: '+56 2 2485 7000',
    latitude: -33.5260,
    longitude: -70.5870,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Ginecología', 'Traumatología', 'Otorrinolaringología', 'Laboratorio'],
    description: 'Clínica integral en La Florida que destaca por su cercanía con la comunidad y atención expedita en urgencias.',
    urgencia: true,
    googleRating: 3.6,
    googleReviews: 2940,
    attendanceRate: '~900 pacientes/día',
  },
  {
    id: 'cp-09',
    name: 'Clínica RedSalud Santiago',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Apoquindo 3990',
    comuna: 'Las Condes',
    phone: '+56 2 2822 0600',
    latitude: -33.4120,
    longitude: -70.5810,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía Ambulatoria', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Parte de la red RedSalud, ofrece atención accesible con múltiples especialidades y convenios.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 2380,
    attendanceRate: '~750 pacientes/día',
  },
  {
    id: 'cp-10',
    name: 'Clínica MEDS',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Isabel La Católica 3740',
    comuna: 'Las Condes',
    phone: '+56 2 2916 3000',
    latitude: -33.3980,
    longitude: -70.5580,
    hours: 'Lunes a Sábado 8:00 - 20:00',
    services: ['Traumatología Deportiva', 'Kinesiología', 'Cirugía Ortopédica', 'Medicina Deportiva', 'Imagenología', 'Rehabilitación'],
    description: 'Clínica especializada en medicina deportiva y traumatología, referente en Chile para deportistas.',
    urgencia: false,
    googleRating: 4.4,
    googleReviews: 6120,
    attendanceRate: '~600 pacientes/día',
  },
  {
    id: 'cp-11',
    name: 'Clínica Tabancura',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Tabancura 1185',
    comuna: 'Vitacura',
    phone: '+56 2 2210 7000',
    latitude: -33.3930,
    longitude: -70.5770,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Maternidad', 'Pediatría', 'Ginecología', 'Traumatología'],
    description: 'Clínica del grupo Red de Salud UC CHRISTUS en Vitacura, con énfasis en maternidad y atención pediátrica.',
    urgencia: true,
    googleRating: 4.0,
    googleReviews: 3210,
    attendanceRate: '~800 pacientes/día',
  },
  {
    id: 'cp-12',
    name: 'Clínica RedSalud Providencia',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Salvador 130',
    comuna: 'Providencia',
    phone: '+56 2 2592 5000',
    latitude: -33.4370,
    longitude: -70.6240,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía Ambulatoria', 'Ginecología', 'Dermatología', 'Oftalmología', 'Laboratorio'],
    description: 'Centro de salud de la red RedSalud con atención integral en el corazón de Providencia.',
    urgencia: true,
    googleRating: 3.7,
    googleReviews: 2670,
    attendanceRate: '~680 pacientes/día',
  },
  {
    id: 'cp-13',
    name: 'Clínica Dávila Vespucio',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Vicuña Mackenna 6570',
    comuna: 'La Florida',
    phone: '+56 2 2730 9000',
    latitude: -33.5140,
    longitude: -70.5990,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Pediatría', 'Ginecología', 'Traumatología', 'UCI', 'Imagenología'],
    description: 'Extensión de Clínica Dávila en el sector suroriente de Santiago con moderna infraestructura y convenios Fonasa.',
    urgencia: true,
    googleRating: 3.9,
    googleReviews: 4180,
    attendanceRate: '~1.150 pacientes/día',
  },
  {
    id: 'cp-14',
    name: 'Clínica UC CHRISTUS',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Lira 40',
    comuna: 'Santiago',
    phone: '+56 2 2354 3000',
    latitude: -33.4440,
    longitude: -70.6430,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina Interna', 'Cirugía', 'Cardiología', 'Oncología', 'Neurocirugía', 'Trasplantes', 'UCI'],
    description: 'Centro médico académico de la Pontificia Universidad Católica, uno de los mejores centros de salud de América Latina.',
    urgencia: true,
    googleRating: 4.5,
    googleReviews: 9870,
    attendanceRate: '~2.000 pacientes/día',
  },
  {
    id: 'cp-15',
    name: 'Clínica Bupa Santiago',
    type: 'clinica_privada',
    typeLabel: 'Clínica Privada',
    address: 'Av. Manuel Montt 115',
    comuna: 'Providencia',
    phone: '+56 2 2366 7000',
    latitude: -33.4310,
    longitude: -70.6200,
    hours: '24 horas',
    services: ['Urgencia', 'Medicina General', 'Cirugía', 'Cardiología', 'Ginecología', 'Traumatología', 'Imagenología'],
    description: 'Parte de la red internacional Bupa, ofrece estándares de salud globales con enfoque en prevención.',
    urgencia: true,
    googleRating: 3.8,
    googleReviews: 3450,
    attendanceRate: '~950 pacientes/día',
  },

  // ═══════════════════════════════════════
  // CESFAM (15)
  // ═══════════════════════════════════════
  {
    id: 'ces-01',
    name: 'CESFAM Nº1 Ramón Corbalán Melgarejo',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Portugal 205',
    comuna: 'Santiago',
    phone: '+56 2 2639 4920',
    latitude: -33.4480,
    longitude: -70.6380,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Programa de Vacunación', 'Control de Embarazo'],
    description: 'Centro de salud familiar en Santiago Centro con atención primaria integral y enfoque preventivo.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 1240,
    attendanceRate: '~350 pacientes/día',
  },
  {
    id: 'ces-02',
    name: 'CESFAM Cristo Vive',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Recoleta 3601',
    comuna: 'Recoleta',
    phone: '+56 2 2621 7880',
    latitude: -33.4100,
    longitude: -70.6420,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Medicina Complementaria', 'Salud Mental', 'Kinesiología'],
    description: 'Centro de salud con enfoque intercultural en Recoleta, reconocido por integrar medicina complementaria y atención a población migrante.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 890,
    attendanceRate: '~320 pacientes/día',
  },
  {
    id: 'ces-03',
    name: 'CESFAM Lo Barnechea',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Lo Barnechea 1101',
    comuna: 'Lo Barnechea',
    phone: '+56 2 2216 8700',
    latitude: -33.3550,
    longitude: -70.5200,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Programa del Adulto Mayor', 'Vacunación', 'Control de Niño Sano'],
    description: 'Centro de salud familiar que atiende a la comunidad de Lo Barnechea con programas de salud preventiva.',
    urgencia: false,
    googleRating: 3.6,
    googleReviews: 640,
    attendanceRate: '~280 pacientes/día',
  },
  {
    id: 'ces-04',
    name: 'CESFAM Padre Gerardo Whelan',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. José Joaquín Pérez 8630',
    comuna: 'Cerro Navia',
    phone: '+56 2 2640 1250',
    latitude: -33.4260,
    longitude: -70.7380,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Kinesiología', 'Nutrición'],
    description: 'CESFAM comunitario en Cerro Navia con fuerte enfoque en salud familiar y participación comunitaria.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 710,
    attendanceRate: '~400 pacientes/día',
  },
  {
    id: 'ces-05',
    name: 'CESFAM San Alberto Hurtado',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Concha y Toro 1820',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 6300',
    latitude: -33.5700,
    longitude: -70.5850,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Programa Cardiovascular', 'Vacunación', 'Salud Mental'],
    description: 'Centro de salud familiar en Puente Alto que brinda atención primaria a una de las comunas más pobladas.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 980,
    attendanceRate: '~450 pacientes/día',
  },
  {
    id: 'ces-06',
    name: 'CESFAM Carol Urzúa Ibáñez',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Lo Ovalle 01650',
    comuna: 'Pedro Aguirre Cerda',
    phone: '+56 2 2556 2100',
    latitude: -33.4830,
    longitude: -70.6640,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Kinesiología', 'Programa de Lactancia', 'Nutrición'],
    description: 'Centro de salud familiar en Pedro Aguirre Cerda, orientado a la atención integral con énfasis en salud materno-infantil.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 560,
    attendanceRate: '~310 pacientes/día',
  },
  {
    id: 'ces-07',
    name: 'CESFAM Lo Hermida',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Grecia 8777',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 5500',
    latitude: -33.4780,
    longitude: -70.5530,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Terapia Ocupacional', 'Podología'],
    description: 'Centro de salud comunitario en Peñalolén con larga trayectoria de servicio a la comunidad de Lo Hermida.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 830,
    attendanceRate: '~370 pacientes/día',
  },
  {
    id: 'ces-08',
    name: 'CESFAM Juan Antonio Ríos',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. El Guanaco 1331',
    comuna: 'Independencia',
    phone: '+56 2 2737 3200',
    latitude: -33.4080,
    longitude: -70.6600,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Programa del Adulto Mayor', 'Control Prenatal', 'Vacunación'],
    description: 'CESFAM en la comuna de Independencia que atiende a la población del sector norte con programas preventivos.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 620,
    attendanceRate: '~340 pacientes/día',
  },
  {
    id: 'ces-09',
    name: 'CESFAM Bellavista de La Florida',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Bellavista 3450',
    comuna: 'La Florida',
    phone: '+56 2 2281 1900',
    latitude: -33.5250,
    longitude: -70.5930,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Nutrición', 'Programa Cardiovascular'],
    description: 'Centro de salud en La Florida con fuerte presencia comunitaria y programas de estilos de vida saludable.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 740,
    attendanceRate: '~380 pacientes/día',
  },
  {
    id: 'ces-10',
    name: 'CESFAM El Roble',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Santa Rosa 12850',
    comuna: 'La Pintana',
    phone: '+56 2 2542 7800',
    latitude: -33.5600,
    longitude: -70.6340,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Kinesiología', 'Vacunación', 'Salud Mental'],
    description: 'CESFAM de La Pintana enfocado en la atención primaria integral con programas de salud comunitaria.',
    urgencia: false,
    googleRating: 2.7,
    googleReviews: 510,
    attendanceRate: '~420 pacientes/día',
  },
  {
    id: 'ces-11',
    name: 'CESFAM Ñuñoa',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Irarrázaval 4054',
    comuna: 'Ñuñoa',
    phone: '+56 2 2239 4500',
    latitude: -33.4540,
    longitude: -70.6010,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Kinesiología', 'Control de Niño Sano'],
    description: 'Centro de salud familiar de Ñuñoa con enfoque preventivo y de promoción de la salud.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 920,
    attendanceRate: '~330 pacientes/día',
  },
  {
    id: 'ces-12',
    name: 'CESFAM Maipú',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Los Pajaritos 3391',
    comuna: 'Maipú',
    phone: '+56 2 2531 8200',
    latitude: -33.5090,
    longitude: -70.7640,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Nutrición', 'Programa Cardiovascular', 'Vacunación'],
    description: 'CESFAM de Maipú que atiende a gran cantidad de población del sector poniente con programas de salud familiar.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 1120,
    attendanceRate: '~480 pacientes/día',
  },
  {
    id: 'ces-13',
    name: 'CESFAM Quilicura',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. San Martín 540',
    comuna: 'Quilicura',
    phone: '+56 2 2948 3600',
    latitude: -33.3630,
    longitude: -70.7340,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Programa del Adulto Mayor', 'Vacunación'],
    description: 'Centro de salud de Quilicura con atención intercultural para la diversa población de la comuna norponiente.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 680,
    attendanceRate: '~410 pacientes/día',
  },
  {
    id: 'ces-14',
    name: 'CESFAM La Reina',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Príncipe de Gales 6832',
    comuna: 'La Reina',
    phone: '+56 2 2273 6100',
    latitude: -33.4490,
    longitude: -70.5450,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Nutrición', 'Kinesiología', 'Programa de Vacunación'],
    description: 'Centro de salud familiar de La Reina con enfoque en atención primaria de calidad y salud preventiva.',
    urgencia: false,
    googleRating: 3.6,
    googleReviews: 530,
    attendanceRate: '~260 pacientes/día',
  },
  {
    id: 'ces-15',
    name: 'CESFAM Macul',
    type: 'cesfam',
    typeLabel: 'CESFAM',
    address: 'Av. Macul 3450',
    comuna: 'Macul',
    phone: '+56 2 2238 9200',
    latitude: -33.4740,
    longitude: -70.5940,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría', 'Ginecología', 'Odontología', 'Salud Mental', 'Terapia Ocupacional', 'Control Prenatal'],
    description: 'CESFAM de Macul con fuerte vínculo comunitario y programas orientados a la salud familiar integral.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 470,
    attendanceRate: '~290 pacientes/día',
  },

  // ═══════════════════════════════════════
  // SAPU - Servicio de Atención Primaria de Urgencia (20)
  // ═══════════════════════════════════════
  {
    id: 'sapu-01',
    name: 'SAPU CESFAM Nº1 Santiago',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Portugal 205',
    comuna: 'Santiago',
    phone: '+56 2 2639 4925',
    latitude: -33.4483,
    longitude: -70.6375,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Derivación Hospitalaria'],
    description: 'Servicio de atención primaria de urgencia adosado al CESFAM Nº1 de Santiago Centro, atiende urgencias de baja y mediana complejidad en horarios no hábiles.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 620,
    attendanceRate: '~180 pacientes/noche',
  },
  {
    id: 'sapu-02',
    name: 'SAPU Conchalí',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Independencia 4250',
    comuna: 'Conchalí',
    phone: '+56 2 2713 3500',
    latitude: -33.3890,
    longitude: -70.6530,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Derivación'],
    description: 'SAPU que brinda atención de urgencia primaria a la comunidad de Conchalí fuera del horario habitual de los centros de salud.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 430,
    attendanceRate: '~150 pacientes/noche',
  },
  {
    id: 'sapu-03',
    name: 'SAPU El Bosque',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Santa Rosa 9530',
    comuna: 'El Bosque',
    phone: '+56 2 2528 7100',
    latitude: -33.5460,
    longitude: -70.6580,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Estabilización'],
    description: 'Servicio de urgencia primaria para la población de El Bosque, operativo en horarios extendidos.',
    urgencia: true,
    googleRating: 2.7,
    googleReviews: 520,
    attendanceRate: '~200 pacientes/noche',
  },
  {
    id: 'sapu-04',
    name: 'SAPU Estación Central',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Libertador Bernardo O Higgins 3865',
    comuna: 'Estación Central',
    phone: '+56 2 2779 3200',
    latitude: -33.4530,
    longitude: -70.6940,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Derivación Hospitalaria'],
    description: 'SAPU de Estación Central que cubre la demanda de urgencias primarias del sector centro-poniente de Santiago.',
    urgencia: true,
    googleRating: 2.6,
    googleReviews: 390,
    attendanceRate: '~170 pacientes/noche',
  },
  {
    id: 'sapu-05',
    name: 'SAPU Huechuraba',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Recoleta 8300',
    comuna: 'Huechuraba',
    phone: '+56 2 2624 5300',
    latitude: -33.3690,
    longitude: -70.6350,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Derivación'],
    description: 'Servicio de atención primaria de urgencia de Huechuraba, cubriendo la demanda nocturna y de fines de semana.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 310,
    attendanceRate: '~130 pacientes/noche',
  },
  {
    id: 'sapu-06',
    name: 'SAPU La Cisterna',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. El Parrón 725',
    comuna: 'La Cisterna',
    phone: '+56 2 2558 4100',
    latitude: -33.5330,
    longitude: -70.6620,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Estabilización'],
    description: 'SAPU que atiende a la comunidad de La Cisterna con atención de urgencia primaria en horarios no hábiles.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 370,
    attendanceRate: '~160 pacientes/noche',
  },
  {
    id: 'sapu-07',
    name: 'SAPU La Granja',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Santa Rosa 8290',
    comuna: 'La Granja',
    phone: '+56 2 2522 8500',
    latitude: -33.5310,
    longitude: -70.6240,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Derivación Hospitalaria'],
    description: 'Servicio de urgencia primaria de La Granja, operativo fuera de horario de los consultorios.',
    urgencia: true,
    googleRating: 2.5,
    googleReviews: 480,
    attendanceRate: '~210 pacientes/noche',
  },
  {
    id: 'sapu-08',
    name: 'SAPU Lo Espejo',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Central 501',
    comuna: 'Lo Espejo',
    phone: '+56 2 2568 3400',
    latitude: -33.5190,
    longitude: -70.6880,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Derivación'],
    description: 'SAPU de Lo Espejo para atención de urgencias primarias fuera de horario hábil.',
    urgencia: true,
    googleRating: 2.6,
    googleReviews: 290,
    attendanceRate: '~140 pacientes/noche',
  },
  {
    id: 'sapu-09',
    name: 'SAPU Lo Prado',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. San Pablo 5800',
    comuna: 'Lo Prado',
    phone: '+56 2 2774 2100',
    latitude: -33.4430,
    longitude: -70.7250,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Estabilización'],
    description: 'Servicio de atención primaria de urgencia en Lo Prado, atendiendo demanda nocturna del sector poniente.',
    urgencia: true,
    googleRating: 2.7,
    googleReviews: 340,
    attendanceRate: '~155 pacientes/noche',
  },
  {
    id: 'sapu-10',
    name: 'SAPU Pudahuel',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. La Estrella 401',
    comuna: 'Pudahuel',
    phone: '+56 2 2749 5200',
    latitude: -33.4420,
    longitude: -70.7530,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Derivación Hospitalaria'],
    description: 'SAPU de Pudahuel que atiende urgencias primarias de la extensa comuna del sector norponiente.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 410,
    attendanceRate: '~185 pacientes/noche',
  },
  {
    id: 'sapu-11',
    name: 'SAPU Quinta Normal',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Carrascal 3550',
    comuna: 'Quinta Normal',
    phone: '+56 2 2774 1600',
    latitude: -33.4310,
    longitude: -70.7020,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Derivación'],
    description: 'Servicio de urgencia primaria de Quinta Normal para atención en horarios extendidos.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 350,
    attendanceRate: '~165 pacientes/noche',
  },
  {
    id: 'sapu-12',
    name: 'SAPU Renca',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Domingo Santa María 3550',
    comuna: 'Renca',
    phone: '+56 2 2641 2800',
    latitude: -33.4040,
    longitude: -70.7190,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Estabilización'],
    description: 'SAPU de Renca con atención de urgencias primarias para la comunidad en horario no hábil.',
    urgencia: true,
    googleRating: 2.7,
    googleReviews: 290,
    attendanceRate: '~145 pacientes/noche',
  },
  {
    id: 'sapu-13',
    name: 'SAPU San Joaquín',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Vicuña Mackenna 4850',
    comuna: 'San Joaquín',
    phone: '+56 2 2556 8700',
    latitude: -33.4940,
    longitude: -70.6280,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Derivación Hospitalaria'],
    description: 'Servicio de urgencia primaria de San Joaquín para la población del sector sur-oriente de Santiago.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 380,
    attendanceRate: '~175 pacientes/noche',
  },
  {
    id: 'sapu-14',
    name: 'SAPU Cerrillos',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Pedro Aguirre Cerda 6500',
    comuna: 'Cerrillos',
    phone: '+56 2 2557 4300',
    latitude: -33.4960,
    longitude: -70.7120,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Derivación'],
    description: 'SAPU de Cerrillos para atención de urgencias nocturnas y de fin de semana.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 260,
    attendanceRate: '~120 pacientes/noche',
  },
  {
    id: 'sapu-15',
    name: 'SAPU San Ramón',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Santa Rosa 8750',
    comuna: 'San Ramón',
    phone: '+56 2 2522 9100',
    latitude: -33.5380,
    longitude: -70.6420,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Estabilización'],
    description: 'Servicio de atención primaria de urgencia en San Ramón, adosado al consultorio central.',
    urgencia: true,
    googleRating: 2.6,
    googleReviews: 350,
    attendanceRate: '~190 pacientes/noche',
  },
  {
    id: 'sapu-16',
    name: 'SAPU Colina',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Chiloé 100',
    comuna: 'Colina',
    phone: '+56 2 2844 7500',
    latitude: -33.2030,
    longitude: -70.6710,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Derivación'],
    description: 'SAPU de Colina que atiende urgencias primarias de la creciente comuna de la provincia de Chacabuco.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 280,
    attendanceRate: '~130 pacientes/noche',
  },
  {
    id: 'sapu-17',
    name: 'SAPU Lampa',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. José Manuel Balmaceda 300',
    comuna: 'Lampa',
    phone: '+56 2 2595 3800',
    latitude: -33.2860,
    longitude: -70.8770,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Derivación Hospitalaria'],
    description: 'Servicio de urgencia primaria para la comuna de Lampa, en la provincia de Chacabuco.',
    urgencia: true,
    googleRating: 2.8,
    googleReviews: 210,
    attendanceRate: '~100 pacientes/noche',
  },
  {
    id: 'sapu-18',
    name: 'SAPU Buin',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. San Martín 425',
    comuna: 'Buin',
    phone: '+56 2 2821 3400',
    latitude: -33.7320,
    longitude: -70.7400,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Estabilización'],
    description: 'SAPU de la comuna de Buin que brinda atención de urgencia primaria al sector sur de la RM.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 190,
    attendanceRate: '~90 pacientes/noche',
  },
  {
    id: 'sapu-19',
    name: 'SAPU Talagante',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Bernardo O Higgins 560',
    comuna: 'Talagante',
    phone: '+56 2 2815 7200',
    latitude: -33.6630,
    longitude: -70.9260,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Suturas Menores', 'Derivación'],
    description: 'Servicio de atención primaria de urgencia de Talagante, provincia de Talagante.',
    urgencia: true,
    googleRating: 2.9,
    googleReviews: 170,
    attendanceRate: '~85 pacientes/noche',
  },
  {
    id: 'sapu-20',
    name: 'SAPU Melipilla',
    type: 'sapu',
    typeLabel: 'SAPU',
    address: 'Av. Ortúzar 515',
    comuna: 'Melipilla',
    phone: '+56 2 2832 1500',
    latitude: -33.6870,
    longitude: -71.2130,
    hours: 'Lunes a Viernes 17:00 - 8:00, Sábado, Domingo y Festivos 24 horas',
    services: ['Urgencia Primaria', 'Curaciones', 'Inyecciones', 'Nebulizaciones', 'Control de Signos Vitales', 'Derivación Hospitalaria'],
    description: 'SAPU de Melipilla con atención de urgencia primaria para la provincia de Melipilla.',
    urgencia: true,
    googleRating: 2.7,
    googleReviews: 240,
    attendanceRate: '~110 pacientes/noche',
  },

  // ═══════════════════════════════════════
  // SAR - Servicio de Atención Primaria de Urgencia de Alta Resolución (12)
  // ═══════════════════════════════════════
  {
    id: 'sar-01',
    name: 'SAR Maipú',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Tres Poniente 1155',
    comuna: 'Maipú',
    phone: '+56 2 2571 8400',
    latitude: -33.5050,
    longitude: -70.7580,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio Básico', 'Estabilización Avanzada', 'Sala de Observación', 'Procedimientos Menores'],
    description: 'Servicio de urgencia primaria de alta resolución en Maipú con capacidad de imagenología y laboratorio, reduciendo derivaciones hospitalarias.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 1240,
    attendanceRate: '~350 pacientes/día',
  },
  {
    id: 'sar-02',
    name: 'SAR La Florida',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. La Florida 9500',
    comuna: 'La Florida',
    phone: '+56 2 2576 9500',
    latitude: -33.5280,
    longitude: -70.5840,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio Básico', 'Estabilización Avanzada', 'Sala de Observación', 'Electrocardiograma'],
    description: 'SAR de La Florida con capacidad de resolver urgencias de mediana complejidad sin necesidad de derivación hospitalaria.',
    urgencia: true,
    googleRating: 3.5,
    googleReviews: 980,
    attendanceRate: '~320 pacientes/día',
  },
  {
    id: 'sar-03',
    name: 'SAR Puente Alto',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Concha y Toro 2450',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 6800',
    latitude: -33.5760,
    longitude: -70.5790,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación', 'Estabilización', 'Nebulizaciones'],
    description: 'Servicio de urgencia de alta resolución en Puente Alto para descongestionar el Hospital Sótero del Río.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 1560,
    attendanceRate: '~400 pacientes/día',
  },
  {
    id: 'sar-04',
    name: 'SAR El Bosque',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Lo Martínez 1620',
    comuna: 'El Bosque',
    phone: '+56 2 2528 7500',
    latitude: -33.5510,
    longitude: -70.6630,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio Básico', 'Sala de Observación', 'Procedimientos Menores', 'Electrocardiograma'],
    description: 'SAR de El Bosque que complementa la red de urgencia del sector sur de Santiago.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 870,
    attendanceRate: '~280 pacientes/día',
  },
  {
    id: 'sar-05',
    name: 'SAR Peñalolén',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Grecia 9250',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 5800',
    latitude: -33.4810,
    longitude: -70.5430,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Estabilización Avanzada', 'Sala de Observación', 'Suturas'],
    description: 'Servicio de alta resolución de Peñalolén, disminuyendo la carga en las urgencias hospitalarias del sector oriente.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 720,
    attendanceRate: '~250 pacientes/día',
  },
  {
    id: 'sar-06',
    name: 'SAR San Bernardo',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Colón 1480',
    comuna: 'San Bernardo',
    phone: '+56 2 2488 6500',
    latitude: -33.5950,
    longitude: -70.7010,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio Básico', 'Sala de Observación', 'Electrocardiograma', 'Estabilización'],
    description: 'SAR de San Bernardo que fortalece la red de urgencia del sector sur-poniente de la Región Metropolitana.',
    urgencia: true,
    googleRating: 3.2,
    googleReviews: 650,
    attendanceRate: '~270 pacientes/día',
  },
  {
    id: 'sar-07',
    name: 'SAR Quilicura',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Lo Marcoleta 830',
    comuna: 'Quilicura',
    phone: '+56 2 2948 3900',
    latitude: -33.3580,
    longitude: -70.7300,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación', 'Procedimientos Menores', 'Nebulizaciones'],
    description: 'SAR de Quilicura para la atención de urgencias de mediana complejidad en el sector norponiente.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 540,
    attendanceRate: '~230 pacientes/día',
  },
  {
    id: 'sar-08',
    name: 'SAR La Pintana',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Santa Rosa 12300',
    comuna: 'La Pintana',
    phone: '+56 2 2542 7900',
    latitude: -33.5570,
    longitude: -70.6310,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio Básico', 'Estabilización', 'Sala de Observación', 'Suturas'],
    description: 'Servicio de urgencia de alta resolución en La Pintana que permite resolver casos sin derivación hospitalaria.',
    urgencia: true,
    googleRating: 3.0,
    googleReviews: 610,
    attendanceRate: '~290 pacientes/día',
  },
  {
    id: 'sar-09',
    name: 'SAR Pudahuel',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. La Estrella 920',
    comuna: 'Pudahuel',
    phone: '+56 2 2749 5500',
    latitude: -33.4400,
    longitude: -70.7580,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación', 'Electrocardiograma', 'Procedimientos Menores'],
    description: 'SAR de Pudahuel con capacidad de diagnóstico avanzado para urgencias primarias del sector norponiente.',
    urgencia: true,
    googleRating: 3.2,
    googleReviews: 430,
    attendanceRate: '~200 pacientes/día',
  },
  {
    id: 'sar-10',
    name: 'SAR Conchalí',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Independencia 4600',
    comuna: 'Conchalí',
    phone: '+56 2 2713 3700',
    latitude: -33.3860,
    longitude: -70.6560,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio Básico', 'Estabilización Avanzada', 'Sala de Observación', 'Nebulizaciones'],
    description: 'SAR de Conchalí para resolver urgencias de mediana complejidad en el sector norte de Santiago.',
    urgencia: true,
    googleRating: 3.1,
    googleReviews: 480,
    attendanceRate: '~220 pacientes/día',
  },
  {
    id: 'sar-11',
    name: 'SAR Padre Hurtado',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Camilo Henríquez 455',
    comuna: 'Padre Hurtado',
    phone: '+56 2 2811 4200',
    latitude: -33.5710,
    longitude: -70.8280,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio', 'Sala de Observación', 'Estabilización', 'Procedimientos Menores'],
    description: 'SAR de Padre Hurtado que atiende urgencias de alta resolución en la provincia de Talagante.',
    urgencia: true,
    googleRating: 3.3,
    googleReviews: 320,
    attendanceRate: '~180 pacientes/día',
  },
  {
    id: 'sar-12',
    name: 'SAR Colina',
    type: 'sar',
    typeLabel: 'SAR',
    address: 'Av. Chiloé 250',
    comuna: 'Colina',
    phone: '+56 2 2844 7800',
    latitude: -33.2010,
    longitude: -70.6750,
    hours: '24 horas',
    services: ['Urgencia Alta Resolución', 'Imagenología', 'Laboratorio Básico', 'Sala de Observación', 'Electrocardiograma', 'Suturas'],
    description: 'SAR de Colina con atención de urgencia de alta resolución para la creciente población de la provincia de Chacabuco.',
    urgencia: true,
    googleRating: 3.4,
    googleReviews: 390,
    attendanceRate: '~190 pacientes/día',
  },

  // ═══════════════════════════════════════
  // COSAM - Centro de Salud Mental Comunitario (18)
  // ═══════════════════════════════════════
  {
    id: 'cosam-01',
    name: 'COSAM Santiago',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Matta 1028',
    comuna: 'Santiago',
    phone: '+56 2 2555 3100',
    latitude: -33.4560,
    longitude: -70.6430,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Trabajo Social', 'Rehabilitación Psicosocial', 'Atención de Adicciones'],
    description: 'Centro de salud mental comunitario de Santiago Centro, brindando atención especializada en psiquiatría y rehabilitación psicosocial.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 520,
    attendanceRate: '~120 pacientes/día',
  },
  {
    id: 'cosam-02',
    name: 'COSAM Pudahuel',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. La Estrella 1130',
    comuna: 'Pudahuel',
    phone: '+56 2 2749 6100',
    latitude: -33.4380,
    longitude: -70.7560,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Trabajo Social', 'Programa de Drogas y Alcohol', 'Rehabilitación'],
    description: 'Centro comunitario de salud mental de Pudahuel con programas de prevención y tratamiento de adicciones.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 340,
    attendanceRate: '~100 pacientes/día',
  },
  {
    id: 'cosam-03',
    name: 'COSAM Peñalolén',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Los Presidentes 8920',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 6100',
    latitude: -33.4830,
    longitude: -70.5470,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología Infanto-Juvenil', 'Terapia Ocupacional', 'Trabajo Social', 'Intervención Familiar', 'Programa SENDA'],
    description: 'COSAM de Peñalolén con enfoque en salud mental infanto-juvenil y programas comunitarios de prevención.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 410,
    attendanceRate: '~110 pacientes/día',
  },
  {
    id: 'cosam-04',
    name: 'COSAM La Florida',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Walker Martínez 5645',
    comuna: 'La Florida',
    phone: '+56 2 2281 2200',
    latitude: -33.5170,
    longitude: -70.5900,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Trabajo Social', 'Programa de Adicciones', 'Intervención en Crisis'],
    description: 'Centro de salud mental comunitario de La Florida, atendiendo a la comuna más poblada de Santiago.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 560,
    attendanceRate: '~130 pacientes/día',
  },
  {
    id: 'cosam-05',
    name: 'COSAM Maipú',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. 5 de Abril 2750',
    comuna: 'Maipú',
    phone: '+56 2 2531 8600',
    latitude: -33.5110,
    longitude: -70.7520,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Trabajo Social', 'Programa Drogas y Alcohol', 'Rehabilitación Psicosocial'],
    description: 'COSAM de Maipú con amplio programa de salud mental comunitaria y rehabilitación para el sector poniente.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 470,
    attendanceRate: '~125 pacientes/día',
  },
  {
    id: 'cosam-06',
    name: 'COSAM Puente Alto',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Tocornal 130',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 6900',
    latitude: -33.6090,
    longitude: -70.5790,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Programa Infanto-Juvenil', 'Trabajo Social', 'Programa SENDA'],
    description: 'Centro de salud mental de Puente Alto con atención integral en salud mental para todas las edades.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 640,
    attendanceRate: '~140 pacientes/día',
  },
  {
    id: 'cosam-07',
    name: 'COSAM San Bernardo',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Colón 1350',
    comuna: 'San Bernardo',
    phone: '+56 2 2488 6800',
    latitude: -33.5910,
    longitude: -70.7030,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia de Grupo', 'Trabajo Social', 'Rehabilitación', 'Programa de Adicciones'],
    description: 'COSAM de San Bernardo con programas de salud mental comunitaria y rehabilitación psicosocial.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 380,
    attendanceRate: '~105 pacientes/día',
  },
  {
    id: 'cosam-08',
    name: 'COSAM Ñuñoa',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. José Domingo Cañas 2590',
    comuna: 'Ñuñoa',
    phone: '+56 2 2239 4800',
    latitude: -33.4530,
    longitude: -70.6050,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Intervención Familiar', 'Trabajo Social', 'Talleres Terapéuticos'],
    description: 'Centro de salud mental comunitario de Ñuñoa con enfoque integral y comunitario en la atención psicosocial.',
    urgencia: false,
    googleRating: 3.7,
    googleReviews: 320,
    attendanceRate: '~95 pacientes/día',
  },
  {
    id: 'cosam-09',
    name: 'COSAM Recoleta',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. El Salto 2980',
    comuna: 'Recoleta',
    phone: '+56 2 2621 8200',
    latitude: -33.4060,
    longitude: -70.6330,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Intercultural', 'Trabajo Social', 'Programa de Adicciones', 'Intervención en Crisis'],
    description: 'COSAM de Recoleta con atención intercultural en salud mental, incluyendo programas para población migrante.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 290,
    attendanceRate: '~100 pacientes/día',
  },
  {
    id: 'cosam-10',
    name: 'COSAM Lo Espejo',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Central 620',
    comuna: 'Lo Espejo',
    phone: '+56 2 2568 3600',
    latitude: -33.5210,
    longitude: -70.6910,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Trabajo Social', 'Programa Infanto-Juvenil', 'Rehabilitación'],
    description: 'Centro de salud mental de Lo Espejo con programas orientados a niños, adolescentes y familias vulnerables.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 210,
    attendanceRate: '~80 pacientes/día',
  },
  {
    id: 'cosam-11',
    name: 'COSAM El Bosque',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Lo Martínez 1300',
    comuna: 'El Bosque',
    phone: '+56 2 2528 7300',
    latitude: -33.5480,
    longitude: -70.6610,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Trabajo Social', 'Programa de Drogas', 'Talleres Terapéuticos'],
    description: 'COSAM de El Bosque con enfoque en prevención de consumo de sustancias y rehabilitación comunitaria.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 250,
    attendanceRate: '~90 pacientes/día',
  },
  {
    id: 'cosam-12',
    name: 'COSAM Estación Central',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Ecuador 4140',
    comuna: 'Estación Central',
    phone: '+56 2 2779 3400',
    latitude: -33.4510,
    longitude: -70.6980,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Trabajo Social', 'Programa de Adicciones', 'Intervención Familiar'],
    description: 'Centro comunitario de salud mental de Estación Central con programas de prevención y tratamiento.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 270,
    attendanceRate: '~85 pacientes/día',
  },
  {
    id: 'cosam-13',
    name: 'COSAM Independencia',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Vivaceta 1630',
    comuna: 'Independencia',
    phone: '+56 2 2737 3400',
    latitude: -33.4110,
    longitude: -70.6650,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Trabajo Social', 'Rehabilitación Psicosocial', 'Programa SENDA'],
    description: 'COSAM de Independencia con atención integral en salud mental y programas de rehabilitación.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 230,
    attendanceRate: '~80 pacientes/día',
  },
  {
    id: 'cosam-14',
    name: 'COSAM La Pintana',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Santa Rosa 13100',
    comuna: 'La Pintana',
    phone: '+56 2 2542 8100',
    latitude: -33.5630,
    longitude: -70.6370,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Trabajo Social', 'Programa de Adicciones', 'Intervención Comunitaria'],
    description: 'Centro de salud mental de La Pintana con fuerte compromiso comunitario y programas de rehabilitación.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 310,
    attendanceRate: '~110 pacientes/día',
  },
  {
    id: 'cosam-15',
    name: 'COSAM Quilicura',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Lo Marcoleta 660',
    comuna: 'Quilicura',
    phone: '+56 2 2948 4100',
    latitude: -33.3600,
    longitude: -70.7320,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Intercultural', 'Trabajo Social', 'Programa Infanto-Juvenil', 'Rehabilitación'],
    description: 'COSAM de Quilicura con atención intercultural en salud mental para la diversa población de la comuna.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 280,
    attendanceRate: '~90 pacientes/día',
  },
  {
    id: 'cosam-16',
    name: 'COSAM Cerro Navia',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. José Joaquín Pérez 8300',
    comuna: 'Cerro Navia',
    phone: '+56 2 2640 1500',
    latitude: -33.4280,
    longitude: -70.7350,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Trabajo Social', 'Programa de Drogas y Alcohol', 'Talleres'],
    description: 'Centro de salud mental de Cerro Navia con programas de prevención y tratamiento de adicciones.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 190,
    attendanceRate: '~85 pacientes/día',
  },
  {
    id: 'cosam-17',
    name: 'COSAM San Miguel',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Departamental 240',
    comuna: 'San Miguel',
    phone: '+56 2 2556 9200',
    latitude: -33.4950,
    longitude: -70.6510,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Familiar', 'Trabajo Social', 'Rehabilitación Psicosocial', 'Programa SENDA'],
    description: 'COSAM de San Miguel con atención integral en salud mental para la comunidad del sector sur.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 260,
    attendanceRate: '~95 pacientes/día',
  },
  {
    id: 'cosam-18',
    name: 'COSAM Renca',
    type: 'cosam',
    typeLabel: 'COSAM',
    address: 'Av. Domingo Santa María 3300',
    comuna: 'Renca',
    phone: '+56 2 2641 3100',
    latitude: -33.4060,
    longitude: -70.7160,
    hours: 'Lunes a Viernes 8:30 - 17:30',
    services: ['Psiquiatría', 'Psicología', 'Terapia Ocupacional', 'Trabajo Social', 'Intervención en Crisis', 'Programa de Adicciones'],
    description: 'Centro comunitario de salud mental de Renca con programas de rehabilitación e intervención en crisis.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 200,
    attendanceRate: '~75 pacientes/día',
  },

  // ═══════════════════════════════════════
  // CECOF - Centro Comunitario de Salud Familiar (18)
  // ═══════════════════════════════════════
  {
    id: 'cecof-01',
    name: 'CECOF Villa Portales',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Las Encinas 3490',
    comuna: 'Estación Central',
    phone: '+56 2 2779 3500',
    latitude: -33.4560,
    longitude: -70.6910,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Control de Embarazo', 'Vacunación', 'Programa de Crónicos', 'Talleres de Salud', 'Visitas Domiciliarias'],
    description: 'Centro comunitario de salud familiar en Estación Central, brindando atención primaria cercana a la comunidad.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 180,
    attendanceRate: '~80 pacientes/día',
  },
  {
    id: 'cecof-02',
    name: 'CECOF Lo Hermida',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Grecia 8550',
    comuna: 'Peñalolén',
    phone: '+56 2 2277 5600',
    latitude: -33.4760,
    longitude: -70.5550,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Programa del Adulto Mayor', 'Vacunación', 'Curaciones', 'Talleres Comunitarios', 'Visitas Domiciliarias'],
    description: 'CECOF de Lo Hermida en Peñalolén, acercando la atención primaria a la comunidad local.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 150,
    attendanceRate: '~70 pacientes/día',
  },
  {
    id: 'cecof-03',
    name: 'CECOF Villa O Higgins',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Santa Rosa 9100',
    comuna: 'La Granja',
    phone: '+56 2 2522 8700',
    latitude: -33.5350,
    longitude: -70.6200,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría Básica', 'Control Prenatal', 'Vacunación', 'Programa de Crónicos', 'Talleres de Salud'],
    description: 'Centro comunitario de salud familiar en La Granja, descentralizando la atención primaria para la comunidad.',
    urgencia: false,
    googleRating: 2.7,
    googleReviews: 130,
    attendanceRate: '~65 pacientes/día',
  },
  {
    id: 'cecof-04',
    name: 'CECOF San Joaquín Sur',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Vicuña Mackenna 5100',
    comuna: 'San Joaquín',
    phone: '+56 2 2556 8900',
    latitude: -33.4980,
    longitude: -70.6250,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Control de Niño Sano', 'Vacunación', 'Programa del Adulto Mayor', 'Curaciones', 'Visitas Domiciliarias'],
    description: 'CECOF de San Joaquín que acerca la atención primaria a los sectores más alejados de los consultorios principales.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 140,
    attendanceRate: '~60 pacientes/día',
  },
  {
    id: 'cecof-05',
    name: 'CECOF Bajos de Mena',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Gabriela 3450',
    comuna: 'Puente Alto',
    phone: '+56 2 2850 7100',
    latitude: -33.6190,
    longitude: -70.5810,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Pediatría Básica', 'Control Prenatal', 'Vacunación', 'Programa de Crónicos', 'Talleres Comunitarios'],
    description: 'Centro comunitario de salud familiar en el sector de Bajos de Mena, Puente Alto, acercando la salud a sectores vulnerables.',
    urgencia: false,
    googleRating: 2.6,
    googleReviews: 280,
    attendanceRate: '~90 pacientes/día',
  },
  {
    id: 'cecof-06',
    name: 'CECOF Lo Prado Norte',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. San Pablo 5450',
    comuna: 'Lo Prado',
    phone: '+56 2 2774 2300',
    latitude: -33.4410,
    longitude: -70.7200,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Control de Crónicos', 'Curaciones', 'Programa del Adulto Mayor', 'Visitas Domiciliarias'],
    description: 'CECOF del sector norte de Lo Prado con atención primaria comunitaria.',
    urgencia: false,
    googleRating: 2.9,
    googleReviews: 120,
    attendanceRate: '~55 pacientes/día',
  },
  {
    id: 'cecof-07',
    name: 'CECOF Pedro Aguirre Cerda',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Club Hípico 3200',
    comuna: 'Pedro Aguirre Cerda',
    phone: '+56 2 2556 2300',
    latitude: -33.4810,
    longitude: -70.6700,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Control Prenatal', 'Vacunación', 'Programa de Crónicos', 'Talleres de Salud', 'Curaciones'],
    description: 'Centro comunitario de salud familiar en Pedro Aguirre Cerda, acercando servicios básicos de salud a la comunidad.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 110,
    attendanceRate: '~50 pacientes/día',
  },
  {
    id: 'cecof-08',
    name: 'CECOF Tiltil',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Calle Principal 450',
    comuna: 'Tiltil',
    phone: '+56 2 2595 4200',
    latitude: -33.0870,
    longitude: -70.9250,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Control de Crónicos', 'Curaciones', 'Visitas Domiciliarias', 'Programa Rural'],
    description: 'CECOF de Tiltil que lleva atención primaria a esta comuna rural de la provincia de Chacabuco.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 80,
    attendanceRate: '~35 pacientes/día',
  },
  {
    id: 'cecof-09',
    name: 'CECOF San José de Maipo',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Camino al Volcán 240',
    comuna: 'San José de Maipo',
    phone: '+56 2 2861 2100',
    latitude: -33.6390,
    longitude: -70.3510,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Programa de Crónicos', 'Control Prenatal', 'Visitas Domiciliarias'],
    description: 'Centro comunitario de salud familiar en San José de Maipo, cubriendo las necesidades de salud primaria de la zona cordillerana.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 90,
    attendanceRate: '~30 pacientes/día',
  },
  {
    id: 'cecof-10',
    name: 'CECOF Pirque',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Ramón Subercaseaux 3120',
    comuna: 'Pirque',
    phone: '+56 2 2854 3200',
    latitude: -33.6530,
    longitude: -70.5980,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Control de Niño Sano', 'Programa del Adulto Mayor', 'Visitas Domiciliarias'],
    description: 'CECOF de Pirque que brinda atención de salud primaria a la comunidad rural de esta comuna precordillerana.',
    urgencia: false,
    googleRating: 3.5,
    googleReviews: 70,
    attendanceRate: '~25 pacientes/día',
  },
  {
    id: 'cecof-11',
    name: 'CECOF Calera de Tango',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Calera de Tango 400',
    comuna: 'Calera de Tango',
    phone: '+56 2 2855 1400',
    latitude: -33.6310,
    longitude: -70.7730,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Control Prenatal', 'Programa de Crónicos', 'Talleres Comunitarios'],
    description: 'Centro comunitario de salud familiar en Calera de Tango, atendiendo a la población de esta comuna semirrural.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 60,
    attendanceRate: '~25 pacientes/día',
  },
  {
    id: 'cecof-12',
    name: 'CECOF Paine',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Arturo Prat 280',
    comuna: 'Paine',
    phone: '+56 2 2824 5100',
    latitude: -33.8090,
    longitude: -70.7410,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Control de Crónicos', 'Visitas Domiciliarias', 'Programa Rural'],
    description: 'CECOF de Paine con atención primaria para la población rural y semiurbana de esta comuna del sur de la RM.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 85,
    attendanceRate: '~35 pacientes/día',
  },
  {
    id: 'cecof-13',
    name: 'CECOF Isla de Maipo',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Alcalde Gonzalo Pérez 320',
    comuna: 'Isla de Maipo',
    phone: '+56 2 2819 3500',
    latitude: -33.7470,
    longitude: -70.8900,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Control Prenatal', 'Programa de Crónicos', 'Visitas Domiciliarias'],
    description: 'Centro comunitario de salud familiar en Isla de Maipo, provincia de Talagante.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 65,
    attendanceRate: '~30 pacientes/día',
  },
  {
    id: 'cecof-14',
    name: 'CECOF El Monte',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. O Higgins 450',
    comuna: 'El Monte',
    phone: '+56 2 2819 4200',
    latitude: -33.6840,
    longitude: -71.0100,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Control de Niño Sano', 'Programa del Adulto Mayor', 'Programa Rural'],
    description: 'CECOF de El Monte con atención primaria comunitaria para esta comuna de la provincia de Talagante.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 55,
    attendanceRate: '~25 pacientes/día',
  },
  {
    id: 'cecof-15',
    name: 'CECOF Peñaflor',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Balmaceda 1250',
    comuna: 'Peñaflor',
    phone: '+56 2 2812 5800',
    latitude: -33.6120,
    longitude: -70.8780,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Control Prenatal', 'Programa de Crónicos', 'Talleres de Salud'],
    description: 'Centro comunitario de salud familiar de Peñaflor, provincia de Talagante.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 95,
    attendanceRate: '~40 pacientes/día',
  },
  {
    id: 'cecof-16',
    name: 'CECOF María Pinto',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Principal 180',
    comuna: 'María Pinto',
    phone: '+56 2 2831 2400',
    latitude: -33.5110,
    longitude: -71.1170,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Programa de Crónicos', 'Visitas Domiciliarias', 'Programa Rural'],
    description: 'CECOF de María Pinto que lleva atención primaria a esta comuna rural de la provincia de Melipilla.',
    urgencia: false,
    googleRating: 3.3,
    googleReviews: 40,
    attendanceRate: '~20 pacientes/día',
  },
  {
    id: 'cecof-17',
    name: 'CECOF Curacaví',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Av. Ambrosio O Higgins 650',
    comuna: 'Curacaví',
    phone: '+56 2 2831 3100',
    latitude: -33.4010,
    longitude: -71.1410,
    hours: 'Lunes a Viernes 8:00 - 17:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Control Prenatal', 'Programa del Adulto Mayor', 'Visitas Domiciliarias'],
    description: 'Centro comunitario de salud familiar de Curacaví, provincia de Melipilla.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 75,
    attendanceRate: '~30 pacientes/día',
  },
  {
    id: 'cecof-18',
    name: 'CECOF Alhué',
    type: 'cecof',
    typeLabel: 'CECOF',
    address: 'Calle Villa Alhué 120',
    comuna: 'Alhué',
    phone: '+56 2 2831 4500',
    latitude: -34.0280,
    longitude: -71.0600,
    hours: 'Lunes a Viernes 8:00 - 16:00',
    services: ['Medicina General', 'Vacunación', 'Curaciones', 'Visitas Domiciliarias', 'Programa Rural', 'Control de Crónicos'],
    description: 'CECOF de Alhué, la comuna más austral y rural de la Región Metropolitana, brindando atención primaria esencial.',
    urgencia: false,
    googleRating: 3.4,
    googleReviews: 30,
    attendanceRate: '~15 pacientes/día',
  },

  // ═══════════════════════════════════════
  // ASEGURADORAS - Seguros de Salud (15)
  // ═══════════════════════════════════════
  {
    id: 'seg-01',
    name: 'Fonasa - Sucursal Santiago Centro',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Libertador Bernardo O Higgins 1033',
    comuna: 'Santiago',
    phone: '+56 600 360 3000',
    latitude: -33.4430,
    longitude: -70.6540,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Consultas de Cobertura', 'Programa GES/AUGE', 'Reembolsos'],
    description: 'Sucursal principal de Fonasa en Santiago Centro. El Fondo Nacional de Salud es el seguro público que cubre al 80% de la población chilena.',
    urgencia: false,
    googleRating: 2.5,
    googleReviews: 3420,
    attendanceRate: '~500 atenciones/día',
  },
  {
    id: 'seg-02',
    name: 'Fonasa - Sucursal Maipú',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Pajaritos 3195',
    comuna: 'Maipú',
    phone: '+56 600 360 3000',
    latitude: -33.5070,
    longitude: -70.7600,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Consultas de Cobertura', 'Programa GES/AUGE', 'Reembolsos'],
    description: 'Sucursal de Fonasa en Maipú para atención de usuarios del sector poniente de Santiago.',
    urgencia: false,
    googleRating: 2.4,
    googleReviews: 1890,
    attendanceRate: '~350 atenciones/día',
  },
  {
    id: 'seg-03',
    name: 'Fonasa - Sucursal Puente Alto',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Concha y Toro 60',
    comuna: 'Puente Alto',
    phone: '+56 600 360 3000',
    latitude: -33.6110,
    longitude: -70.5760,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Consultas de Cobertura', 'Programa GES/AUGE', 'Reembolsos'],
    description: 'Oficina de Fonasa en Puente Alto, atendiendo a la comuna más poblada de Chile.',
    urgencia: false,
    googleRating: 2.3,
    googleReviews: 2150,
    attendanceRate: '~400 atenciones/día',
  },
  {
    id: 'seg-04',
    name: 'Fonasa - Sucursal La Florida',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Vicuña Mackenna 6100',
    comuna: 'La Florida',
    phone: '+56 600 360 3000',
    latitude: -33.5130,
    longitude: -70.6010,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Consultas de Cobertura', 'Programa GES/AUGE', 'Reembolsos'],
    description: 'Sucursal de Fonasa en La Florida para el sector suroriente de Santiago.',
    urgencia: false,
    googleRating: 2.6,
    googleReviews: 1670,
    attendanceRate: '~320 atenciones/día',
  },
  {
    id: 'seg-05',
    name: 'Fonasa - Sucursal San Bernardo',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Colón 580',
    comuna: 'San Bernardo',
    phone: '+56 600 360 3000',
    latitude: -33.5930,
    longitude: -70.6990,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Consultas de Cobertura', 'Programa GES/AUGE', 'Reembolsos'],
    description: 'Oficina de Fonasa en San Bernardo para el sector sur-poniente de la RM.',
    urgencia: false,
    googleRating: 2.5,
    googleReviews: 1230,
    attendanceRate: '~280 atenciones/día',
  },
  {
    id: 'seg-06',
    name: 'Isapre Banmédica - Sucursal Providencia',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Apoquindo 3600',
    comuna: 'Las Condes',
    phone: '+56 600 600 3600',
    latitude: -33.4170,
    longitude: -70.5960,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Licencias Médicas', 'Programa GES', 'Consultas de Cobertura'],
    description: 'Sucursal de Isapre Banmédica, una de las principales aseguradoras privadas de salud en Chile.',
    urgencia: false,
    googleRating: 3.2,
    googleReviews: 2340,
    attendanceRate: '~200 atenciones/día',
  },
  {
    id: 'seg-07',
    name: 'Isapre Colmena - Sucursal Santiago',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Providencia 1909',
    comuna: 'Providencia',
    phone: '+56 600 600 8100',
    latitude: -33.4320,
    longitude: -70.6130,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Licencias Médicas', 'Programa GES', 'Atención al Cliente'],
    description: 'Isapre Colmena Golden Cross, aseguradora privada de salud con amplia red de prestadores.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 1890,
    attendanceRate: '~180 atenciones/día',
  },
  {
    id: 'seg-08',
    name: 'Isapre Cruz Blanca - Sucursal Las Condes',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Apoquindo 4700',
    comuna: 'Las Condes',
    phone: '+56 600 600 2200',
    latitude: -33.4100,
    longitude: -70.5740,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Licencias Médicas', 'Programa GES', 'Consultas de Cobertura'],
    description: 'Isapre Cruz Blanca, parte del grupo Bupa, ofrece planes de salud con cobertura nacional.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 2670,
    attendanceRate: '~220 atenciones/día',
  },
  {
    id: 'seg-09',
    name: 'Isapre Consalud - Sucursal Santiago',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Libertador Bernardo O Higgins 1146',
    comuna: 'Santiago',
    phone: '+56 600 600 2700',
    latitude: -33.4450,
    longitude: -70.6510,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Licencias Médicas', 'Programa GES', 'Atención al Cliente'],
    description: 'Isapre Consalud, una de las aseguradoras privadas con mayor número de afiliados en Chile.',
    urgencia: false,
    googleRating: 2.8,
    googleReviews: 3120,
    attendanceRate: '~250 atenciones/día',
  },
  {
    id: 'seg-10',
    name: 'Isapre Vida Tres - Sucursal Providencia',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Providencia 2653',
    comuna: 'Providencia',
    phone: '+56 600 600 8300',
    latitude: -33.4280,
    longitude: -70.6070,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Licencias Médicas', 'Programa GES', 'Consultas de Cobertura'],
    description: 'Isapre Vida Tres, aseguradora de salud privada del grupo Banmédica con planes familiares e individuales.',
    urgencia: false,
    googleRating: 3.0,
    googleReviews: 1450,
    attendanceRate: '~160 atenciones/día',
  },
  {
    id: 'seg-11',
    name: 'Isapre Nueva Masvida - Sucursal Santiago',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Apoquindo 3076',
    comuna: 'Las Condes',
    phone: '+56 600 600 6700',
    latitude: -33.4190,
    longitude: -70.5890,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Licencias Médicas', 'Programa GES', 'Atención al Cliente'],
    description: 'Isapre Nueva Masvida con planes de salud accesibles y amplia red de prestadores a nivel nacional.',
    urgencia: false,
    googleRating: 2.7,
    googleReviews: 1780,
    attendanceRate: '~190 atenciones/día',
  },
  {
    id: 'seg-12',
    name: 'Fonasa - Sucursal Melipilla',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Ortúzar 350',
    comuna: 'Melipilla',
    phone: '+56 600 360 3000',
    latitude: -33.6880,
    longitude: -71.2110,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Consultas de Cobertura', 'Programa GES/AUGE', 'Reembolsos'],
    description: 'Sucursal de Fonasa en Melipilla para usuarios de la provincia de Melipilla.',
    urgencia: false,
    googleRating: 2.6,
    googleReviews: 680,
    attendanceRate: '~150 atenciones/día',
  },
  {
    id: 'seg-13',
    name: 'Fonasa - Sucursal Quilicura',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Manuel Antonio Matta 798',
    comuna: 'Quilicura',
    phone: '+56 600 360 3000',
    latitude: -33.3650,
    longitude: -70.7370,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Consultas de Cobertura', 'Programa GES/AUGE', 'Reembolsos'],
    description: 'Oficina de Fonasa en Quilicura para la comunidad del sector norponiente.',
    urgencia: false,
    googleRating: 2.4,
    googleReviews: 920,
    attendanceRate: '~230 atenciones/día',
  },
  {
    id: 'seg-14',
    name: 'Isapre Banmédica - Sucursal La Florida',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Vicuña Mackenna 6850',
    comuna: 'La Florida',
    phone: '+56 600 600 3600',
    latitude: -33.5190,
    longitude: -70.5960,
    hours: 'Lunes a Viernes 9:00 - 18:00',
    services: ['Afiliación', 'Planes de Salud', 'Reembolsos', 'Licencias Médicas', 'Programa GES', 'Consultas de Cobertura'],
    description: 'Sucursal de Isapre Banmédica en La Florida para afiliados del sector suroriente.',
    urgencia: false,
    googleRating: 3.1,
    googleReviews: 1340,
    attendanceRate: '~170 atenciones/día',
  },
  {
    id: 'seg-15',
    name: 'Fonasa - Sucursal Talagante',
    type: 'aseguradora',
    typeLabel: 'Aseguradora',
    address: 'Av. Bernardo O Higgins 420',
    comuna: 'Talagante',
    phone: '+56 600 360 3000',
    latitude: -33.6650,
    longitude: -70.9240,
    hours: 'Lunes a Viernes 8:30 - 14:00',
    services: ['Afiliación', 'Bonos de Atención', 'Licencias Médicas', 'Consultas de Cobertura', 'Programa GES/AUGE', 'Reembolsos'],
    description: 'Sucursal de Fonasa en Talagante para la provincia de Talagante.',
    urgencia: false,
    googleRating: 2.7,
    googleReviews: 540,
    attendanceRate: '~130 atenciones/día',
  },
];
